# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/openapi/openapi.json

from __future__ import annotations
from typing import Any, Literal, Mapping, Optional, Union
from pydantic import ValidationError
from .. import _models as models
from .._runtime import (
    NebulaCore,
    RequestOptions,
    prepare_generated_body as _prepare_generated_body,
    validate_request_body as _validate_request_body,
    validate_response as _validate_response,
)


class ClientResource:
    def __init__(self, core: NebulaCore) -> None:
        self._core = core

    async def health(
        self,
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.GenericMessageResponse:
        """Readiness probe

        Returns 200 only after required bootstrap collections, the database pool, and graph storage are ready to serve requests. Use `/v1/liveness` for a process-only probe.

        operationId: client.health
        endpoint: GET /v1/health
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/health",
            "path_params": {},
            "query": None,
            "headers": None,
            "retryable": True,
            "http_semantically_idempotent": True,
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return models.GenericMessageResponse.model_validate(_raw)
        except (ValidationError, ValueError):
            return _raw  # type: ignore[return-value]
