# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/openapi/openapi.json

from __future__ import annotations
from typing import Any, Literal, Mapping, Optional, Union
from pydantic import ValidationError
from .. import _models as models
from .. import _inputs as inputs
from .._runtime import (
    NebulaCore,
    RequestOptions,
    prepare_generated_body as _prepare_generated_body,
    validate_request_body as _validate_request_body,
    validate_response as _validate_response,
)


class EnterpriseResource:
    def __init__(self, core: NebulaCore) -> None:
        self._core = core

    async def provision_account(
        self,
        body: Union[inputs.EnterpriseProvisioningInput, models.EnterpriseProvisioningRequest, Mapping[str, Any]],
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.EnterpriseProvisioningResult:
        """Provision an enterprise account

        Create a user, named collection, and API key as one operation.

        operationId: enterprise.provisionAccount
        endpoint: POST /v1/admin/enterprise-provisioning
        """
        body = _prepare_generated_body(body, [{"path":["request_id"],"kind":"uuid"}])
        body = _validate_request_body(models.EnterpriseProvisioningRequest, body)
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/admin/enterprise-provisioning",
            "path_params": {},
            "query": None,
            "headers": None,
            "body": body,
            "retryable": True,
            "http_semantically_idempotent": False,
            "mutation_replay_identity": {"source":"body","name":"request_id","generated":"uuid"},
            "utf8_byte_limits": [{"source":"body","path":["collection_name"],"maximum":256}],
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return models.EnterpriseProvisioningResult.model_validate(_raw)
