# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/openapi/openapi.json

from __future__ import annotations
from typing import Any, Literal, Mapping, Optional, Union
from pydantic import ValidationError
from .. import _models as models
from .. import _inputs as inputs
from .._runtime import (
    NebulaCore,
    RequestOptions,
    prepare_generated_body as _prepare_generated_body,
    validate_request_body as _validate_request_body,
    validate_response as _validate_response,
)


class IngestionOperationResource:
    def __init__(self, core: NebulaCore) -> None:
        self._core = core

    async def cancel(
        self,
        operation_id: str,
        *,
        collection_id: str,
        request_options: Optional[RequestOptions] = None
    ) -> models.IngestionOperationStatus:
        """Cancel an ingestion operation

        Cancel unfinished items and fence their active generations.

        operationId: ingestionOperation.cancel
        endpoint: POST /v1/ingestion-operations/{operation_id}/cancel
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/ingestion-operations/{operation_id}/cancel",
            "path_params": {"operation_id": operation_id},
            "query": None,
            "headers": None,
            "routing": {"owner": "collection", "value": collection_id},
            "retryable": True,
            "http_semantically_idempotent": False,
            "mutation_replay_identity": {"source":"intrinsic","name":"operation_id"},
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return models.IngestionOperationStatus.model_validate(_raw)

    async def create(
        self,
        body: Union[inputs.CreateIngestionOperationInput, models.CreateIngestionOperationRequest, Mapping[str, Any]],
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.IngestionOperationStatus:
        """Create an ingestion operation

        Create an open ingestion operation for one collection.

        operationId: ingestionOperation.create
        endpoint: POST /v1/ingestion-operations
        """
        body = _prepare_generated_body(body, [{"path":["operation_id"],"kind":"uuid"}])
        body = _validate_request_body(models.CreateIngestionOperationRequest, body)
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/ingestion-operations",
            "path_params": {},
            "query": None,
            "headers": None,
            "body": body,
            "routing": {"owner": "collection", "body_fields": ["collection_id","collectionId"]},
            "retryable": True,
            "http_semantically_idempotent": False,
            "mutation_replay_identity": {"source":"body","name":"operation_id","generated":"uuid"},
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return models.IngestionOperationStatus.model_validate(_raw)

    async def get(
        self,
        operation_id: str,
        *,
        collection_id: str,
        request_options: Optional[RequestOptions] = None
    ) -> models.IngestionOperationStatus:
        """Get an ingestion operation

        Get per-item ingestion, search, and processing readiness.

        operationId: ingestionOperation.get
        endpoint: GET /v1/ingestion-operations/{operation_id}
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/ingestion-operations/{operation_id}",
            "path_params": {"operation_id": operation_id},
            "query": None,
            "headers": None,
            "routing": {"owner": "collection", "value": collection_id},
            "retryable": True,
            "http_semantically_idempotent": True,
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return models.IngestionOperationStatus.model_validate(_raw)

    async def get_many(
        self,
        body: Union[models.BatchedOperationStatusRequest, Mapping[str, Any]],
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.BatchedOperationStatusResponse:
        """Get batched ingestion operation status

        Get ordered status views for multiple ingestion operations.

        operationId: ingestionOperation.getMany
        endpoint: POST /v1/ingestion-operations/status
        """
        body = _validate_request_body(models.BatchedOperationStatusRequest, body)
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/ingestion-operations/status",
            "path_params": {},
            "query": None,
            "headers": None,
            "body": body,
            "retryable": True,
            "http_semantically_idempotent": False,
            "mutation_replay_identity": {"source":"intrinsic","name":"resource_set"},
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return models.BatchedOperationStatusResponse.model_validate(_raw)

    async def put_item(
        self,
        operation_id: str,
        body: Union[inputs.IngestionOperationItemInputInput, models.IngestionOperationItemInput, Mapping[str, Any]],
        *,
        collection_id: str,
        request_options: Optional[RequestOptions] = None
    ) -> models.IngestionOperationStatus:
        """Add or replay an ingestion operation item

        Add or replay one memory under a stable client item key.

        operationId: ingestionOperation.putItem
        endpoint: PUT /v1/ingestion-operations/{operation_id}/items
        """
        body = _prepare_generated_body(body, [{"path":["memory","memory_id"],"kind":"uuid"}])
        body = _validate_request_body(models.IngestionOperationItemInput, body)
        _raw = await self._core.request({
            "method": "PUT",
            "path": "/v1/ingestion-operations/{operation_id}/items",
            "path_params": {"operation_id": operation_id},
            "query": None,
            "headers": None,
            "body": body,
            "routing": {"owner": "collection", "value": collection_id},
            "retryable": True,
            "http_semantically_idempotent": True,
            "mutation_replay_identity": {"source":"body","name":"item_key"},
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return models.IngestionOperationStatus.model_validate(_raw)

    async def seal(
        self,
        operation_id: str,
        *,
        collection_id: str,
        request_options: Optional[RequestOptions] = None
    ) -> models.IngestionOperationStatus:
        """Seal an ingestion operation

        Seal an operation so its item set cannot change.

        operationId: ingestionOperation.seal
        endpoint: POST /v1/ingestion-operations/{operation_id}/seal
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/ingestion-operations/{operation_id}/seal",
            "path_params": {"operation_id": operation_id},
            "query": None,
            "headers": None,
            "routing": {"owner": "collection", "value": collection_id},
            "retryable": True,
            "http_semantically_idempotent": False,
            "mutation_replay_identity": {"source":"intrinsic","name":"operation_id"},
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return models.IngestionOperationStatus.model_validate(_raw)

    async def search_barrier(
        self,
        body: Union[models.SearchBarrierRequest, Mapping[str, Any]],
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.SearchBarrierResponse:
        """Wait for ingestion operation search visibility

        Wait until successful items are visible to memory search.

        operationId: ingestionOperation.searchBarrier
        endpoint: POST /v1/ingestion-operations/search-barrier
        """
        body = _validate_request_body(models.SearchBarrierRequest, body)
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/ingestion-operations/search-barrier",
            "path_params": {},
            "query": None,
            "headers": None,
            "body": body,
            "retryable": True,
            "http_semantically_idempotent": False,
            "mutation_replay_identity": {"source":"intrinsic","name":"resource_set"},
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return models.SearchBarrierResponse.model_validate(_raw)
