# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/openapi/openapi.json

from __future__ import annotations
from typing import Any, Literal, Mapping, Optional, Union
from pydantic import ValidationError
from .. import _models as models
from .. import _inputs as inputs
from .._runtime import (
    NebulaCore,
    RequestOptions,
    prepare_generated_body as _prepare_generated_body,
    validate_request_body as _validate_request_body,
    validate_response as _validate_response,
)


class MarketplaceResource:
    def __init__(self, core: NebulaCore) -> None:
        self._core = core

    async def fork(
        self,
        workspace_id: str,
        source_collection_id: str,
        body: Union[inputs.ForkMarketplaceCollectionInput, models.ForkMarketplaceCollectionRequest, Mapping[str, Any]],
        *,
        request_options: Optional[RequestOptions] = None
    ) -> Union[models.CollectionProvisioningResult, models.CollectionActiveResult, models.CollectionDeletingResult, models.CollectionDeletedResult, models.CollectionFailedResult]:
        """Fork a public collection into your personal workspace

        Fork a public collection into your personal workspace.

        The destination must be the caller's personal workspace;
        marketplace forks never land in team workspaces.

        The response reports whether the durable copy is still processing,
        succeeded, or failed. Retry with the same collection_id to recover
        the same result.

        Authentication is required. The forked collection counts toward your plan limits.

        operationId: marketplace.fork
        endpoint: POST /v1/workspaces/{workspace_id}/marketplace/collections/{source_collection_id}/fork
        """
        body = _prepare_generated_body(body, [{"path":["collection_id"],"kind":"uuid"}])
        body = _validate_request_body(models.ForkMarketplaceCollectionRequest, body)
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/workspaces/{workspace_id}/marketplace/collections/{source_collection_id}/fork",
            "path_params": {"workspace_id": workspace_id, "source_collection_id": source_collection_id},
            "query": None,
            "headers": None,
            "body": body,
            "routing": {"owner": "workspace", "path_fields": ["workspace_id","workspaceId"]},
            "retryable": True,
            "http_semantically_idempotent": False,
            "mutation_replay_identity": {"source":"body","name":"collection_id","generated":"uuid"},
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return _validate_response(Union[models.CollectionProvisioningResult, models.CollectionActiveResult, models.CollectionDeletingResult, models.CollectionDeletedResult, models.CollectionFailedResult], _raw)

    async def get_collection(
        self,
        collection_id: str,
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.CollectionResponse:
        """Get details of a public collection

        Get details of a public collection from the marketplace.
        Returns collection metadata including pricing, preview limits, etc.

        operationId: marketplace.getCollection
        endpoint: GET /v1/marketplace/collections/{collection_id}
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/marketplace/collections/{collection_id}",
            "path_params": {"collection_id": collection_id},
            "query": None,
            "headers": None,
            "retryable": True,
            "http_semantically_idempotent": True,
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return models.CollectionResponse.model_validate(_raw)
        except (ValidationError, ValueError):
            return _raw  # type: ignore[return-value]

    async def list_collections(
        self,
        *,
        cursor: Optional[Union[str, None]] = None,
        limit: Optional[int] = None,
        search: Optional[Union[str, None]] = None,
        request_options: Optional[RequestOptions] = None
    ) -> models.PaginatedCollectionResponse:
        """Browse public marketplace collections

        Browse publicly available collections in the marketplace.
        These collections have 'public_preview' or 'marketplace' access tier.

        No authentication required, but authenticated users may see more details.

        operationId: marketplace.listCollections
        endpoint: GET /v1/marketplace/collections
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/marketplace/collections",
            "path_params": {},
            "query": {"cursor": cursor, "limit": limit, "search": search},
            "headers": None,
            "retryable": True,
            "http_semantically_idempotent": True,
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        try:
            return models.PaginatedCollectionResponse.model_validate(_raw)
        except (ValidationError, ValueError):
            return _raw  # type: ignore[return-value]
