# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/openapi/openapi.json

from __future__ import annotations
from typing import Any, Literal, Mapping, Optional, Union
from pydantic import ValidationError
from .. import _models as models
from .. import _inputs as inputs
from .._runtime import (
    NebulaCore,
    RequestOptions,
    prepare_generated_body as _prepare_generated_body,
    validate_request_body as _validate_request_body,
    validate_response as _validate_response,
)


class MemoryResource:
    def __init__(self, core: NebulaCore) -> None:
        self._core = core

    async def append(
        self,
        id: str,
        body: Union[inputs.AppendMemoryInput, models.AppendMemoryRequest, Mapping[str, Any]],
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.MemoryWriteProjection:
        """Append content to an engram

        Append content to an existing engram.

        **For conversation engrams:**
        - Provide `messages` array with content, role, and optional metadata
        - Works like `/conversations/{id}/messages` endpoint

        **For document engrams:**
        - Provide either `raw_text` or `chunks` to append additional content
        - Content will be processed and added to the engram

        operationId: memory.append
        endpoint: POST /v1/memories/{id}/append
        """
        body = _prepare_generated_body(body, [{"path":["idempotency_key"],"kind":"uuid"}])
        body = _validate_request_body(models.AppendMemoryRequest, body)
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memories/{id}/append",
            "path_params": {"id": id},
            "query": None,
            "headers": None,
            "body": body,
            "routing": {"owner": "collection", "body_fields": ["collection_id","collectionId"]},
            "retryable": False,
            "http_semantically_idempotent": False,
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return models.MemoryWriteProjection.model_validate(_raw)

    async def complete_upload(
        self,
        upload_session_id: str,
        body: Union[models.CompleteMultipartUploadRequest, Mapping[str, Any]],
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.CompleteMultipartUploadResponse:
        """Complete multipart upload session

        Finalize an upload session after every multipart upload part has been uploaded.

        operationId: memory.completeUpload
        endpoint: POST /v1/memories/upload/{upload_session_id}/complete
        """
        body = _validate_request_body(models.CompleteMultipartUploadRequest, body)
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memories/upload/{upload_session_id}/complete",
            "path_params": {"upload_session_id": upload_session_id},
            "query": None,
            "headers": None,
            "body": body,
            "retryable": False,
            "http_semantically_idempotent": False,
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return models.CompleteMultipartUploadResponse.model_validate(_raw)
        except (ValidationError, ValueError):
            return _raw  # type: ignore[return-value]

    async def create_event_ticket(
        self,
        body: Union[models.MemoryEventTicketRequest, Mapping[str, Any]],
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.MemoryEventTicketResult:
        """Create a memory lifecycle event ticket

        Mint a short-lived, single-use ticket for one collection-scoped batch of memory write lifecycle events.

        operationId: memory.createEventTicket
        endpoint: POST /v1/memory-event-tickets
        """
        body = _validate_request_body(models.MemoryEventTicketRequest, body)
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memory-event-tickets",
            "path_params": {},
            "query": None,
            "headers": None,
            "body": body,
            "routing": {"owner": "collection", "body_fields": ["collection_id","collectionId"]},
            "retryable": False,
            "http_semantically_idempotent": False,
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return models.MemoryEventTicketResult.model_validate(_raw)

    async def create_upload(
        self,
        filename: str,
        content_type: str,
        file_size: int,
        *,
        collection_id: Optional[Union[str, None]] = None,
        workspace_id: Optional[Union[str, None]] = None,
        request_options: Optional[RequestOptions] = None
    ) -> models.MultipartUploadSessionResponse:
        """Create multipart upload session

        Create a workspace-scoped multipart upload session.

        operationId: memory.createUpload
        endpoint: POST /v1/memories/upload
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memories/upload",
            "path_params": {},
            "query": {"filename": filename, "content_type": content_type, "file_size": file_size, "collection_id": collection_id, "workspace_id": workspace_id},
            "headers": None,
            "routing": {"owner": "collection", "query_fields": ["collection_id","collectionId"]},
            "retryable": False,
            "http_semantically_idempotent": False,
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return models.MultipartUploadSessionResponse.model_validate(_raw)
        except (ValidationError, ValueError):
            return _raw  # type: ignore[return-value]

    async def delete(
        self,
        id: str,
        collection_id: str,
        *,
        request_options: Optional[RequestOptions] = None
    ) -> Union[models.MemoryDeletingResult, models.MemoryDeletionFailedResult]:
        """Delete an engram

        Durably accept a specific engram for deletion.

        operationId: memory.delete
        endpoint: DELETE /v1/memories/{id}
        """
        _raw = await self._core.request({
            "method": "DELETE",
            "path": "/v1/memories/{id}",
            "path_params": {"id": id},
            "query": {"collection_id": collection_id},
            "headers": None,
            "routing": {"owner": "collection", "query_fields": ["collection_id","collectionId"]},
            "retryable": True,
            "http_semantically_idempotent": True,
            "mutation_replay_identity": {"source":"intrinsic","name":"resource_path"},
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return _validate_response(Union[models.MemoryDeletingResult, models.MemoryDeletionFailedResult], _raw)

    async def delete_many(
        self,
        body: Union[inputs.DeleteMemoriesInput, models.DeleteMemoriesRequest, Mapping[str, Any]],
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.DeleteMemoriesResult:
        """Delete one or more engrams

        Durably accept one or more engrams for deletion.

        operationId: memory.deleteMany
        endpoint: POST /v1/memories/delete
        """
        body = _prepare_generated_body(body, [{"path":["operation_id"],"kind":"uuid"}])
        body = _validate_request_body(models.DeleteMemoriesRequest, body)
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memories/delete",
            "path_params": {},
            "query": None,
            "headers": None,
            "body": body,
            "routing": {"owner": "collection", "body_fields": ["collection_id","collectionId"]},
            "retryable": True,
            "http_semantically_idempotent": False,
            "mutation_replay_identity": {"source":"body","name":"operation_id","generated":"uuid"},
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return models.DeleteMemoriesResult.model_validate(_raw)

    async def delete_upload(
        self,
        upload_session_id: str,
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.GenericMessageResponse:
        """Delete a pending upload session

        Delete a pending upload session and its staged object.

        operationId: memory.deleteUpload
        endpoint: DELETE /v1/memories/upload
        """
        _raw = await self._core.request({
            "method": "DELETE",
            "path": "/v1/memories/upload",
            "path_params": {},
            "query": {"upload_session_id": upload_session_id},
            "headers": None,
            "retryable": False,
            "http_semantically_idempotent": True,
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return models.GenericMessageResponse.model_validate(_raw)
        except (ValidationError, ValueError):
            return _raw  # type: ignore[return-value]

    async def get(
        self,
        id: str,
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.MemoryResponse:
        """Retrieve an engram

        Retrieves detailed information about a specific engram by its
        ID.

        This endpoint returns the engram's metadata, status, and system information. It does not
        return the engram's content - use the `/engrams/{id}/download` endpoint for that.

        Users can only retrieve engrams they own or have access to through collections.
        Superusers can retrieve any engram.

        operationId: memory.get
        endpoint: GET /v1/memories/{id}
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/memories/{id}",
            "path_params": {"id": id},
            "query": None,
            "headers": None,
            "retryable": True,
            "http_semantically_idempotent": True,
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return models.MemoryResponse.model_validate(_raw)

    async def list(
        self,
        *,
        ids: Optional[list[str]] = None,
        cursor: Optional[Union[str, None]] = None,
        limit: Optional[int] = None,
        chunks_limit: Optional[Union[int, None]] = None,
        owner_only: Optional[bool] = None,
        collection_ids: Optional[Union[list[str], None]] = None,
        metadata_filters: Optional[Union[str, None]] = None,
        request_options: Optional[RequestOptions] = None
    ) -> models.PaginatedListedMemoryResponse:
        """List engrams

        Returns a cursor-paginated list of engrams the authenticated user
        has access to.

        Results can be filtered by providing specific engram IDs or collection IDs.
        Regular users will only see engrams they own or have access to through
        collections. Superusers can see all engrams.

        The engrams are returned in order of creation time, most recent
        first. The response includes the engram's text field if available.

        operationId: memory.list
        endpoint: GET /v1/memories
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/memories",
            "path_params": {},
            "query": {"ids": ids, "cursor": cursor, "limit": limit, "chunks_limit": chunks_limit, "owner_only": owner_only, "collection_ids": collection_ids, "metadata_filters": metadata_filters},
            "headers": None,
            "retryable": True,
            "http_semantically_idempotent": True,
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        try:
            return models.PaginatedListedMemoryResponse.model_validate(_raw)
        except (ValidationError, ValueError):
            return _raw  # type: ignore[return-value]

    async def recall_workflow(
        self,
        body: Union[models.CursorRecallRequest, models.PredictRecallRequest, models.ResumeRecallRequest, models.EvidenceRecallRequest, models.BootstrapRecallRequest, Mapping[str, Any]],
        *,
        request_options: Optional[RequestOptions] = None
    ) -> dict[str, Any]:
        """Recall workflow patterns by intent

        Workflow-pattern recall over 5 intents.

        * ``cursor`` -- match the caller's anchor against pattern
          canonical states, return ranked patterns + position.
        * ``predict`` -- like cursor but include the predicted next
          trace from each pattern's canonical instance.
        * ``resume`` -- like cursor, biased toward longer patterns.
        * ``evidence`` -- expand a specific pattern via
          ``hydrate_pattern``.
        * ``bootstrap`` -- top-K patterns by confidence with no anchor.

        operationId: memory.recallWorkflow
        endpoint: POST /v1/memories/workflow/recall
        """
        body = _validate_request_body(Union[models.CursorRecallRequest, models.PredictRecallRequest, models.ResumeRecallRequest, models.EvidenceRecallRequest, models.BootstrapRecallRequest], body)
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memories/workflow/recall",
            "path_params": {},
            "query": None,
            "headers": None,
            "body": body,
            "retryable": False,
            "http_semantically_idempotent": False,
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return _raw

    async def resolve_search_sources(
        self,
        retrieval_id: str,
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.RetrievalAuditSourcesResponse:
        """Resolve sources for an audited memory search

        Hydrate stored evidence refs after rechecking current access.

        operationId: memory.resolveSearchSources
        endpoint: GET /v1/memories/searches/{retrieval_id}/sources
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/memories/searches/{retrieval_id}/sources",
            "path_params": {"retrieval_id": retrieval_id},
            "query": None,
            "headers": None,
            "retryable": True,
            "http_semantically_idempotent": True,
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return models.RetrievalAuditSourcesResponse.model_validate(_raw)
        except (ValidationError, ValueError):
            return _raw  # type: ignore[return-value]

    async def search(
        self,
        body: Union[models.MemorySearchRequest, Mapping[str, Any]],
        *,
        request_options: Optional[RequestOptions] = None
    ) -> Union[models.CompactMemoryRecallResponse, models.MemoryRecall, models.SnapshotSearchResult]:
        """Search memories

        Perform a search query across your memories.

        **Standard mode** (collection_ids or readable-scope search): returns hierarchical MemoryRecall
        with semantics, episodes, and procedures. Set ``include_sources``
        to include the raw source material grounding the retrieved memory.

        **Snapshot mode** (snapshot field): returns graph-search results with
        {entities, relationships} from stateless in-memory traversal.

        operationId: memory.search
        endpoint: POST /v1/memories/search
        """
        body = _validate_request_body(models.MemorySearchRequest, body)
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memories/search",
            "path_params": {},
            "query": None,
            "headers": None,
            "body": body,
            "routing": {"owner": "collection", "body_fields": ["collection_ids","collectionIds","filters.collection_id","filters.collection_ids","search_settings.filters.collection_id","search_settings.filters.collection_ids"]},
            "retryable": False,
            "http_semantically_idempotent": False,
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return _validate_response(Union[models.CompactMemoryRecallResponse, models.MemoryRecall, models.SnapshotSearchResult], _raw)
        except (ValidationError, ValueError):
            return _raw  # type: ignore[return-value]

    async def sign_upload_part(
        self,
        upload_session_id: str,
        part_number: int,
        checksum_sha256: str,
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.MultipartUploadPartResponse:
        """Create multipart upload part URL

        Create a presigned URL for uploading one part of an existing memory upload session.

        operationId: memory.signUploadPart
        endpoint: POST /v1/memories/upload/{upload_session_id}/parts/{part_number}
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memories/upload/{upload_session_id}/parts/{part_number}",
            "path_params": {"upload_session_id": upload_session_id, "part_number": part_number},
            "query": {"checksum_sha256": checksum_sha256},
            "headers": None,
            "retryable": False,
            "http_semantically_idempotent": False,
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return models.MultipartUploadPartResponse.model_validate(_raw)
        except (ValidationError, ValueError):
            return _raw  # type: ignore[return-value]

    async def status(
        self,
        body: Union[models.MemoryStatusRequest, Mapping[str, Any]],
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.MemoryStatusResponse:
        """Get authoritative memory write status

        Resolve up to 40 admitted memory writes and optionally wait for exact search visibility or full processing.

        operationId: memory.status
        endpoint: POST /v1/memories/status
        """
        body = _validate_request_body(models.MemoryStatusRequest, body)
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memories/status",
            "path_params": {},
            "query": None,
            "headers": None,
            "body": body,
            "routing": {"owner": "collection", "body_fields": ["collection_id","collectionId"]},
            "retryable": True,
            "http_semantically_idempotent": False,
            "mutation_replay_identity": {"source":"intrinsic","name":"resource_set"},
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return models.MemoryStatusResponse.model_validate(_raw)

    async def store(
        self,
        body: Union[inputs.StoreMemoryInput, models.StoreMemoryRequest, Mapping[str, Any]],
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.MemoryWriteProjection:
        """Store a memory

        Store a conversation or document through one durable product
        surface. Nebula SDKs generate the stable memory identity.

        operationId: memory.store
        endpoint: POST /v1/memories
        """
        body = _prepare_generated_body(body, [{"path":["memory_id"],"kind":"uuid"}])
        body = _validate_request_body(models.StoreMemoryRequest, body)
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memories",
            "path_params": {},
            "query": None,
            "headers": None,
            "body": body,
            "routing": {"owner": "collection", "body_fields": ["collection_id","collectionId"]},
            "retryable": True,
            "http_semantically_idempotent": False,
            "mutation_replay_identity": {"source":"body","name":"memory_id","generated":"uuid"},
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return models.MemoryWriteProjection.model_validate(_raw)

    async def store_many(
        self,
        body: Union[inputs.StoreMemoriesInput, models.StoreMemoriesRequest, Mapping[str, Any]],
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.StoreMemoriesResult:
        """Store a bounded memory batch

        Store up to 40 independent document or conversation memories in one request. Each memory has its own stable identity, processing state, and replay outcome.

        operationId: memory.storeMany
        endpoint: POST /v1/memories/batch
        """
        body = _prepare_generated_body(body, [{"path":["memories","*","memory_id"],"kind":"uuid"}])
        body = _validate_request_body(models.StoreMemoriesRequest, body)
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/memories/batch",
            "path_params": {},
            "query": None,
            "headers": None,
            "body": body,
            "routing": {"owner": "collection", "body_fields": ["collection_id","collectionId"]},
            "retryable": True,
            "http_semantically_idempotent": False,
            "mutation_replay_identity": {"source":"intrinsic","name":"resource_set"},
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return models.StoreMemoriesResult.model_validate(_raw)

    async def update(
        self,
        id: str,
        collection_id: str,
        body: Union[models.UpdateMemoryRequest, Mapping[str, Any]],
        *,
        request_options: Optional[RequestOptions] = None
    ) -> models.MemoryResponse:
        """Update a memory

        Update memory-level properties including name, metadata, and collection associations.

        This endpoint allows updating properties of an entire memory (document or conversation)
        without modifying its content:
        - **name**: Updates the authoritative engram title
        - **metadata**: Can replace or merge with existing metadata
        - **collection_ids**: Updates authoritative engram collection associations

        Users can only update memories they own or have access to through collections.
        At least one collection association must be maintained.

        If collection_id is provided and the engram is shared across collections, a copy-on-write
        will be performed to create a collection-specific copy before modification.

        operationId: memory.update
        endpoint: PATCH /v1/memories/{id}
        """
        body = _validate_request_body(models.UpdateMemoryRequest, body)
        _raw = await self._core.request({
            "method": "PATCH",
            "path": "/v1/memories/{id}",
            "path_params": {"id": id},
            "query": {"collection_id": collection_id},
            "headers": None,
            "body": body,
            "routing": {"owner": "collection", "query_fields": ["collection_id","collectionId"]},
            "retryable": False,
            "http_semantically_idempotent": False,
            "timeout_seconds": request_options.timeout_seconds if request_options else None,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        return models.MemoryResponse.model_validate(_raw)
