# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/openapi/openapi.json

from __future__ import annotations
from typing import Any, Mapping, Optional, Union
from pydantic import ValidationError
from .. import _models as models
from .._runtime import (
    NebulaCore,
    validate_request_body as _validate_request_body,
    validate_response as _validate_response,
)


class SnapshotsResource:
    def __init__(self, core: NebulaCore) -> None:
        self._core = core

    async def export(
        self,
        body: Union[models.SnapshotExportRequest, Mapping[str, Any]]
    ) -> Union[models.SnapshotEnvelopeOutput, models.SnapshotObjectReference]:
        """Export a collection snapshot

        Export a collection's full graph state as a
        portable SnapshotEnvelope.

        operationId: snapshots.export
        endpoint: POST /v1/device-memory/snapshot/export
        """
        body = _validate_request_body(models.SnapshotExportRequest, body)
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/device-memory/snapshot/export",
            "path_params": {},
            "query": None,
            "body": body,
            "idempotent": True,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return _validate_response(Union[models.SnapshotEnvelopeOutput, models.SnapshotObjectReference], _raw)
        except (ValidationError, ValueError):
            return _raw  # type: ignore[return-value]

    async def import_(
        self,
        body: Union[models.SnapshotImportRequest, Mapping[str, Any]]
    ) -> models.SnapshotImportResult:
        """Import a snapshot into an ephemeral collection

        Import a SnapshotEnvelope into an ephemeral
        collection. Returns the ephemeral collection UUID.

        operationId: snapshots.import
        endpoint: POST /v1/device-memory/snapshot/import
        """
        body = _validate_request_body(models.SnapshotImportRequest, body)
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/device-memory/snapshot/import",
            "path_params": {},
            "query": None,
            "body": body,
            "idempotent": False,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return models.SnapshotImportResult.model_validate(_raw)
        except (ValidationError, ValueError):
            return _raw  # type: ignore[return-value]
