# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/openapi/openapi.json

from __future__ import annotations
from typing import Any, Optional, Union
from pydantic import ValidationError
from .. import _models as models
from .._runtime import NebulaCore, validate_response as _validate_response


class WorkspacesResource:
    def __init__(self, core: NebulaCore) -> None:
        self._core = core

    async def create_storage_target(
        self,
        workspace_id: str,
        body: models.StorageTargetCreateRequest
    ) -> models.StorageTargetResponse:
        """Create workspace storage target

        Register a customer S3 bucket for hosted BYOC storage.

        operationId: workspaces.createStorageTarget
        endpoint: POST /v1/workspaces/{workspace_id}/storage-targets
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/workspaces/{workspace_id}/storage-targets",
            "path_params": {"workspace_id": workspace_id},
            "query": None,
            "body": body,
            "idempotent": False,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return models.StorageTargetResponse.model_validate(_raw)
        except (ValidationError, ValueError):
            return _raw  # type: ignore[return-value]

    async def disable_storage_target(
        self,
        workspace_id: str,
        target_id: str
    ) -> models.StorageTargetResponse:
        """Disable workspace storage target

        Disable a customer storage target for future collection binds.

        operationId: workspaces.disableStorageTarget
        endpoint: DELETE /v1/workspaces/{workspace_id}/storage-targets/{target_id}
        """
        _raw = await self._core.request({
            "method": "DELETE",
            "path": "/v1/workspaces/{workspace_id}/storage-targets/{target_id}",
            "path_params": {"workspace_id": workspace_id, "target_id": target_id},
            "query": None,
            "idempotent": False,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return models.StorageTargetResponse.model_validate(_raw)
        except (ValidationError, ValueError):
            return _raw  # type: ignore[return-value]

    async def list_storage_targets(
        self,
        workspace_id: str
    ) -> list[models.StorageTargetResponse]:
        """List workspace storage targets

        List customer-owned object storage targets for a workspace.

        operationId: workspaces.listStorageTargets
        endpoint: GET /v1/workspaces/{workspace_id}/storage-targets
        """
        _raw = await self._core.request({
            "method": "GET",
            "path": "/v1/workspaces/{workspace_id}/storage-targets",
            "path_params": {"workspace_id": workspace_id},
            "query": None,
            "idempotent": True,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return _validate_response(list[models.StorageTargetResponse], _raw)
        except (ValidationError, ValueError):
            return _raw  # type: ignore[return-value]

    async def validate_storage_target(
        self,
        workspace_id: str,
        target_id: str
    ) -> models.StorageTargetResponse:
        """Validate workspace storage target

        Probe a customer storage target and mark it active on success.

        operationId: workspaces.validateStorageTarget
        endpoint: POST /v1/workspaces/{workspace_id}/storage-targets/{target_id}/validate
        """
        _raw = await self._core.request({
            "method": "POST",
            "path": "/v1/workspaces/{workspace_id}/storage-targets/{target_id}/validate",
            "path_params": {"workspace_id": workspace_id, "target_id": target_id},
            "query": None,
            "idempotent": False,
        })
        _raw = _raw["results"] if isinstance(_raw, dict) else getattr(_raw, "results", _raw)
        try:
            return models.StorageTargetResponse.model_validate(_raw)
        except (ValidationError, ValueError):
            return _raw  # type: ignore[return-value]
