# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/openapi/openapi.json

from __future__ import annotations
from typing import Optional
from . import _models as models
from ._runtime import NebulaCore, ClientOptions
from .resources.client import ClientResource
from .resources.collections import CollectionsResource
from .resources.connectors import ConnectorsResource
from .resources.enterprise import EnterpriseResource
from .resources.ingestion_operation import IngestionOperationResource
from .resources.marketplace import MarketplaceResource
from .resources.memory import MemoryResource
from .resources.snapshots import SnapshotsResource
from .resources.workspaces import WorkspacesResource


class NebulaClient:
    def __init__(self, options: Optional[ClientOptions] = None) -> None:
        self._core = NebulaCore(options)
        self.client: ClientResource = ClientResource(self._core)
        self.collections: CollectionsResource = CollectionsResource(self._core)
        self.connectors: ConnectorsResource = ConnectorsResource(self._core)
        self.enterprise: EnterpriseResource = EnterpriseResource(self._core)
        self.ingestion_operation: IngestionOperationResource = IngestionOperationResource(self._core)
        self.marketplace: MarketplaceResource = MarketplaceResource(self._core)
        self.memory: MemoryResource = MemoryResource(self._core)
        self.snapshots: SnapshotsResource = SnapshotsResource(self._core)
        self.workspaces: WorkspacesResource = WorkspacesResource(self._core)

    async def aclose(self) -> None:
        await self._core.aclose()

    async def __aenter__(self) -> "NebulaClient":
        return self

    async def __aexit__(self, *args: object) -> None:
        await self.aclose()
