# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/openapi/openapi.json

from __future__ import annotations

from uuid import UUID, uuid4

from pydantic import Field

from . import _models as models


class CopyCollectionInput(models.CopyCollectionRequest):
    collection_id: UUID = Field(default_factory=uuid4)


class CreateCollectionInput(models.CreateCollectionRequest):
    collection_id: UUID = Field(default_factory=uuid4)


class EnterpriseProvisioningInput(models.EnterpriseProvisioningRequest):
    request_id: UUID = Field(default_factory=uuid4)


class CreateIngestionOperationInput(models.CreateIngestionOperationRequest):
    operation_id: UUID = Field(default_factory=uuid4)


class StoreMemoryBatchItemInput(models.StoreMemoryBatchItem):
    memory_id: UUID = Field(default_factory=uuid4)


class IngestionOperationItemInputInput(models.IngestionOperationItemInput):
    memory: StoreMemoryBatchItemInput


class ForkMarketplaceCollectionInput(models.ForkMarketplaceCollectionRequest):
    collection_id: UUID = Field(default_factory=uuid4)


class AppendMemoryInput(models.AppendMemoryRequest):
    operation_id: UUID = Field(default_factory=uuid4)


class DeleteMemoriesInput(models.DeleteMemoriesRequest):
    operation_id: UUID = Field(default_factory=uuid4)


class StoreMemoryInput(models.StoreMemoryRequest):
    memory_id: UUID = Field(default_factory=uuid4)


class StoreMemoriesInput(models.StoreMemoriesRequest):
    memories: list[StoreMemoryBatchItemInput]
