# generated by datamodel-codegen:
#   filename:  .python-models-openapi.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ActivatedEntity(BaseModel):
    """
    An entity activated during memory traversal with its profile.

    Represents a conceptual node in memory that was activated by the query.
    Contains the full EntityProfile (gestalt) filtered by relevance.
    """

    activation_score: float = Field(0, title='Activation Score')
    category: str | None = Field(None, title='Category')
    id: UUID = Field(..., title='Id')
    name: str = Field(..., title='Name')
    profile: Any = Field(None, title='Profile')


class ActivatedEpisode(BaseModel):
    """
    An episodic nodegroup activated during memory traversal.

    Represents a cluster of temporally related facts/events discovered
    during graph traversal.
    """

    activation_score: float = Field(0, title='Activation Score')
    category: str = Field('episodic', title='Category')
    description: str | None = Field(None, title='Description')
    entity_names: list[str] | None = Field(None, title='Entity Names')
    evidence_ids: list[UUID] | None = Field(None, title='Evidence Ids')
    id: UUID = Field(..., title='Id')
    is_obligation: bool = Field(False, title='Is Obligation')
    member_semantic_ids: list[UUID] | None = Field(None, title='Member Semantic Ids')
    modality: str | None = Field(None, title='Modality')
    n_facts: int = Field(0, title='N Facts')
    name: str = Field(..., title='Name')
    resolved_at: datetime | None = Field(None, title='Resolved At')
    status: str | None = Field(None, title='Status')
    t_last: str | None = Field(None, title='T Last')
    t_start: str | None = Field(None, title='T Start')


class ActivatedProcedure(BaseModel):
    """
    A procedure-like memory activated during memory traversal.

    This includes preference procedures and atomic traces. Distinct from facts
    which are descriptive assertions.
    """

    activation_score: float = Field(0, title='Activation Score')
    confidence: float = Field(0, title='Confidence')
    derivation_type: str = Field('trivial', title='Derivation Type')
    entity_id: UUID | None = Field(None, title='Entity Id')
    entity_name: str | None = Field(None, title='Entity Name')
    id: UUID = Field(..., title='Id')
    is_negated: bool = Field(False, title='Is Negated')
    memory_class: str | None = Field(None, title='Memory Class')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    stability_confidence: float | None = Field(None, title='Stability Confidence')
    statement: str = Field(..., title='Statement')
    truth_confidence: float | None = Field(None, title='Truth Confidence')
    use_confidence: float | None = Field(None, title='Use Confidence')


class ActivatedWorkflowStep(BaseModel):
    """
    A single canonical step inside an activated workflow template.

    Rich context fields (how_this_works, typical_entities, typical_tools,
    causes_next_because) are populated by the template inducer and carry
    forward the observational detail from the instances that built this
    template. They exist so an agent can understand *how* a step works,
    *what tools are used*, and *why* it causes the next step — not just
    *what* the step is.
    """

    canonical_description: str = Field(..., title='Canonical Description')
    causes_next_because: str | None = Field(None, title='Causes Next Because')
    entity_roles: list[str] | None = Field(None, title='Entity Roles')
    goal_category: str = Field(..., title='Goal Category')
    how_this_works: str | None = Field(None, title='How This Works')
    index: int = Field(..., title='Index')
    object_type: str = Field(..., title='Object Type')
    optional: bool = Field(False, title='Optional')
    typical_entities: list[str] | None = Field(None, title='Typical Entities')
    typical_tools: list[str] | None = Field(None, title='Typical Tools')
    variable_slots: list[str] | None = Field(None, title='Variable Slots')
    verb_class: str = Field(..., title='Verb Class')


class Authority(RootModel[float]):
    root: float = Field(
        ..., description='Optional authority score', ge=0.0, le=1.0, title='Authority'
    )


class Content(RootModel[str]):
    root: str = Field(
        ...,
        description='Message content. Use a string for text-only messages or a list of content parts for multimodal content.',
        min_length=1,
        pattern='[\\s\\S]*\\S[\\s\\S]*',
        title='Content',
    )


class Role(Enum):
    """
    Role: 'user', 'assistant', or 'system'
    """

    user = 'user'
    assistant = 'assistant'
    system = 'system'


class Chunk(RootModel[str]):
    root: str = Field(..., min_length=1, pattern='[\\s\\S]*\\S[\\s\\S]*')


class Chunks(RootModel[list[Chunk]]):
    root: list[Chunk] = Field(
        ...,
        description='Pre-processed text chunks to append for document memories.',
        min_length=1,
        title='Chunks',
    )


class RawText(RootModel[str]):
    root: str = Field(
        ...,
        description='Raw text content to append for document memories.',
        min_length=1,
        pattern='[\\s\\S]*\\S[\\s\\S]*',
        title='Raw Text',
    )


class AppendedMessageResponse(BaseModel):
    chunk_ids: list[str] | None = Field(None, title='Chunk Ids')
    message_id: str = Field(..., title='Message Id')


class BootstrapRecallRequest(BaseModel):
    """
    Top-K patterns by confidence with no anchor.

    Used when a caller has no current state but wants to see what
    patterns the collection knows about (onboarding, exploration).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    collection_id: UUID = Field(
        ...,
        description='Collection containing the patterns to recall.',
        title='Collection Id',
    )
    intent: Literal['bootstrap'] = Field('bootstrap', title='Intent')
    top_k: int = Field(
        10, description='Maximum number of pattern hits to return.', title='Top K'
    )


class ChunkEnrichmentSettings(BaseModel):
    """
    Settings for chunk enrichment.

    Model selection for the enrichment LLM call lives in
    ``app.task_llms.chunk_enrichment``; the legacy ``generation_config``
    field was removed in the per-task LLM cleanup pass.
    """

    chunk_enrichment_prompt: str | None = Field(
        'chunk_enrichment',
        description='The prompt to use for chunk enrichment',
        title='Chunk Enrichment Prompt',
    )
    enable_chunk_enrichment: bool = Field(
        False,
        description='Whether to enable chunk enrichment or not',
        title='Enable Chunk Enrichment',
    )
    n_chunks: int = Field(
        2,
        description='The number of preceding and succeeding chunks to include. Defaults to 2.',
        title='N Chunks',
    )


class CollectionActiveResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    failure: None = Field(..., title='Failure')
    id: UUID = Field(..., title='Id')
    state: Literal['active'] = Field(..., title='State')


class CollectionDeletedResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    failure: None = Field(..., title='Failure')
    id: UUID = Field(..., title='Id')
    state: Literal['deleted'] = Field(..., title='State')


class CollectionDeletingDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    collection_id: UUID = Field(..., title='Collection Id')
    state: Literal['deleting'] = Field('deleting', title='State')


class CollectionDeletingPublicApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal['collection_deleting'] = Field(..., title='Code')
    details: CollectionDeletingDetails
    message: str = Field(..., title='Message')
    request_id: str | None = Field(..., title='Request Id')
    type: Literal['conflict'] = Field(..., title='Type')


class CollectionDeletingResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    failure: None = Field(..., title='Failure')
    id: UUID = Field(..., title='Id')
    state: Literal['deleting'] = Field(..., title='State')


class CollectionFailedDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    collection_id: UUID = Field(..., title='Collection Id')
    state: Literal['failed'] = Field('failed', title='State')


class CollectionFailedPublicApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal['collection_failed'] = Field(..., title='Code')
    details: CollectionFailedDetails
    message: str = Field(..., title='Message')
    request_id: str | None = Field(..., title='Request Id')
    type: Literal['conflict'] = Field(..., title='Type')


class CollectionIdentityConflictDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    collection_id: UUID = Field(..., title='Collection Id')


class CollectionIdentityConflictPublicApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal['collection_identity_conflict'] = Field(..., title='Code')
    details: CollectionIdentityConflictDetails
    message: str = Field(..., title='Message')
    request_id: str | None = Field(..., title='Request Id')
    type: Literal['conflict'] = Field(..., title='Type')


class CollectionMutationFailureCode(Enum):
    collection_quota_exceeded = 'collection_quota_exceeded'
    collection_name_conflict = 'collection_name_conflict'
    storage_target_unavailable = 'storage_target_unavailable'
    processing_failed = 'processing_failed'


class CollectionNameConflictDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    collection_id: UUID = Field(..., title='Collection Id')
    name: str = Field(..., title='Name')


class CollectionNameConflictPublicApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal['collection_name_conflict'] = Field(..., title='Code')
    details: CollectionNameConflictDetails
    message: str = Field(..., title='Message')
    request_id: str | None = Field(..., title='Request Id')
    type: Literal['conflict'] = Field(..., title='Type')


class CollectionProvisioningDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    collection_id: UUID = Field(..., title='Collection Id')
    state: Literal['provisioning'] = Field(..., title='State')


class CollectionProvisioningPublicApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal['collection_provisioning'] = Field(..., title='Code')
    details: CollectionProvisioningDetails
    message: str = Field(..., title='Message')
    request_id: str | None = Field(..., title='Request Id')
    type: Literal['conflict'] = Field(..., title='Type')


class CollectionProvisioningResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    failure: None = Field(..., title='Failure')
    id: UUID = Field(..., title='Id')
    state: Literal['provisioning'] = Field(..., title='State')


class CollectionQuotaExceededDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    collection_id: UUID = Field(..., title='Collection Id')
    quota_limit: int = Field(..., title='Quota Limit')


class CollectionQuotaExceededPublicApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal['collection_quota_exceeded'] = Field(..., title='Code')
    details: CollectionQuotaExceededDetails
    message: str = Field(..., title='Message')
    request_id: str | None = Field(..., title='Request Id')
    type: Literal['conflict'] = Field(..., title='Type')


class CollectionResponse(BaseModel):
    access_tier: str | None = Field('private', title='Access Tier')
    cache_policy: str | None = Field('lazy', title='Cache Policy')
    chain_type: str | None = Field(None, title='Chain Type')
    contract_address: str | None = Field(None, title='Contract Address')
    created_at: datetime = Field(..., title='Created At')
    creator_royalty_bps: int | None = Field(250, title='Creator Royalty Bps')
    description: str | None = Field(..., title='Description')
    engram_count: int = Field(..., title='Engram Count')
    graph_collection_status: str = Field(..., title='Graph Collection Status')
    graph_sync_status: str = Field(..., title='Graph Sync Status')
    has_preview_access: bool | None = Field(None, title='Has Preview Access')
    id: UUID = Field(..., title='Id')
    is_marketplace_listed: bool = Field(False, title='Is Marketplace Listed')
    lattice_node_id: UUID | None = Field(None, title='Lattice Node Id')
    marketplace_metadata: dict[str, Any] | None = Field(
        None, title='Marketplace Metadata'
    )
    memory_count: int | None = Field(0, title='Memory Count')
    name: str = Field(..., title='Name')
    nft_collection_address: str | None = Field(None, title='Nft Collection Address')
    owner_email: str | None = Field(None, title='Owner Email')
    owner_id: UUID | None = Field(..., title='Owner Id')
    owner_name: str | None = Field(None, title='Owner Name')
    preview_query_limit: int | None = Field(0, title='Preview Query Limit')
    purchase_price_usd: str | None = Field(None, title='Purchase Price Usd')
    rental_price_monthly_usd: str | None = Field(None, title='Rental Price Monthly Usd')
    storage_target_id: UUID | None = Field(None, title='Storage Target Id')
    updated_at: datetime = Field(..., title='Updated At')
    user_count: int = Field(..., title='User Count')
    workflows_enabled: bool = Field(False, title='Workflows Enabled')
    workspace_id: UUID | None = Field(None, title='Workspace Id')


class CompactMemoryRecallResponse(BaseModel):
    """
    Default compact response from /v1/memories/search.
    """

    episodic: list[dict[str, Any]] | None = Field(None, title='Episodic')
    procedural: list[dict[str, Any]] | None = Field(None, title='Procedural')
    query: str = Field(..., title='Query')
    retrieval_id: UUID | None = Field(
        None,
        description='Stable identifier for retrieval audit and source resolution.',
        title='Retrieval Id',
    )
    semantic: list[dict[str, Any]] | None = Field(None, title='Semantic')
    sources: list[dict[str, Any]] | None = Field(
        None,
        description='Present only when include_sources is true; an empty list means sources were requested but none were found.',
        title='Sources',
    )
    token_count: int = Field(0, title='Token Count')


class CompleteMultipartUploadResponse(BaseModel):
    byte_size: int = Field(..., title='Byte Size')
    content_type: str = Field(..., title='Content Type')
    raw_sha256: str = Field(..., title='Raw Sha256')
    upload_session_id: UUID = Field(..., title='Upload Session Id')


class CompletedMultipartUploadPart(BaseModel):
    checksum_sha256: str = Field(
        ...,
        description='Base64-encoded SHA-256 checksum returned for the part.',
        title='Checksum Sha256',
    )
    etag: str = Field(..., min_length=1, title='Etag')
    part_number: int = Field(..., ge=1, le=10000, title='Part Number')


class ConnectRequest(BaseModel):
    collection_id: UUID = Field(..., title='Collection Id')
    config: dict[str, Any] | None = Field(None, title='Config')
    oauth_client_id: str | None = Field(None, title='Oauth Client Id')
    oauth_client_mode: str | None = Field(None, title='Oauth Client Mode')
    oauth_client_secret: str | None = Field(None, title='Oauth Client Secret')


class ConnectorConnectResponse(BaseModel):
    auth_url: str = Field(..., title='Auth Url')
    state: str = Field(..., title='State')


class Health(Enum):
    ok = 'ok'
    error = 'error'


class Status(Enum):
    active = 'active'
    pending = 'pending'
    revoked = 'revoked'


class ConnectorErrorDetail(BaseModel):
    message: str = Field(..., title='Message')
    retryable: bool = Field(..., title='Retryable')


class ProviderFamily(Enum):
    google = 'google'
    m365 = 'm365'


class ConnectorOAuthAppResponse(BaseModel):
    can_manage: bool = Field(False, title='Can Manage')
    configured: bool = Field(..., title='Configured')
    gmail_pubsub_audience: str | None = Field(None, title='Gmail Pubsub Audience')
    gmail_pubsub_push_service_account: str | None = Field(
        None, title='Gmail Pubsub Push Service Account'
    )
    gmail_pubsub_topic: str | None = Field(None, title='Gmail Pubsub Topic')
    gmail_webhook_url: str | None = Field(None, title='Gmail Webhook Url')
    oauth_client_id: str | None = Field(None, title='Oauth Client Id')
    provider_family: ProviderFamily = Field(..., title='Provider Family')
    updated_at: datetime | None = Field(None, title='Updated At')


class GmailPubsubAudience(RootModel[str]):
    root: str = Field(..., max_length=512, title='Gmail Pubsub Audience')


class GmailPubsubPushServiceAccount(RootModel[str]):
    root: str = Field(..., max_length=320, title='Gmail Pubsub Push Service Account')


class GmailPubsubTopic(RootModel[str]):
    root: str = Field(..., max_length=512, title='Gmail Pubsub Topic')


class ConnectorOAuthAppUpdateRequest(BaseModel):
    collection_id: UUID = Field(..., title='Collection Id')
    gmail_pubsub_audience: GmailPubsubAudience | None = Field(
        None, title='Gmail Pubsub Audience'
    )
    gmail_pubsub_push_service_account: GmailPubsubPushServiceAccount | None = Field(
        None, title='Gmail Pubsub Push Service Account'
    )
    gmail_pubsub_topic: GmailPubsubTopic | None = Field(
        None, title='Gmail Pubsub Topic'
    )


class ConnectorSyncResponse(BaseModel):
    message: str = Field(..., title='Message')


class ConnectorWarning(BaseModel):
    code: str = Field(..., title='Code')
    message: str = Field(..., title='Message')


class ConversationFields(BaseModel):
    """
    Conversation-specific typed fields.

    Present iff ``Engram.kind == CONVERSATION``. Holds the platform-written
    fields that previously lived on ``metadata`` (``conversation_id``,
    ``episode_type``) so they have a typed home and are not co-mingled with
    user-supplied metadata.
    """

    conversation_id: UUID | None = Field(None, title='Conversation Id')
    episode_type: str | None = Field(None, title='Episode Type')


class CreateCollectionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    collection_id: UUID = Field(
        ...,
        description='Stable collection identity generated automatically by Nebula SDKs.',
        title='Collection Id',
    )
    description: str | None = Field(None, title='Description')
    lattice_node_id: UUID | None = Field(
        None,
        description="Team workspace lattice node that owns this collection. Omit to use the workspace's General node. Personal collections cannot set this field.",
        title='Lattice Node Id',
    )
    name: str = Field(
        ..., max_length=256, min_length=1, pattern='[\\s\\S]*\\S[\\s\\S]*', title='Name'
    )
    storage_target_id: UUID | None = Field(
        None,
        description="BYOC storage target to host this collection's graph data. Requires a team workspace and an active target provisioned through the dashboard or workspace storage-target APIs.",
        title='Storage Target Id',
    )
    workflows_enabled: bool = Field(False, title='Workflows Enabled')
    workspace_id: UUID | None = Field(
        None,
        description='Workspace this collection belongs to. Provisioned via the dashboard / management API, not minted through the public SDK.',
        title='Workspace Id',
    )


class CursorRecallRequest(BaseModel):
    """
    Locate where the caller is in known workflows.

    Matches the caller's current state against pattern canonical
    instances' entry states; returns ranked pattern hits with
    pattern-side position metadata.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    collection_id: UUID = Field(
        ...,
        description='Collection containing the patterns to recall.',
        title='Collection Id',
    )
    intent: Literal['cursor'] = Field('cursor', title='Intent')
    state_id: UUID | None = Field(
        None,
        description="Anchor: the user's current state nodegroup id.",
        title='State Id',
    )
    top_k: int = Field(
        10, description='Maximum number of pattern hits to return.', title='Top K'
    )
    trace_id: UUID | None = Field(
        None,
        description="Anchor: the user's most recent trace id. The handler resolves this trace's state_before automatically.",
        title='Trace Id',
    )


class DeleteMemoriesRequest(BaseModel):
    collection_id: UUID = Field(
        ...,
        description='Collection context for the memory deletion.',
        title='Collection Id',
    )
    ids: UUID | list[UUID] = Field(
        ...,
        description='Single engram ID or list of engram IDs to delete.',
        title='Ids',
    )


class DocumentType(Enum):
    """
    Types of file formats that can be stored as engrams.
    """

    mp3 = 'mp3'
    csv = 'csv'
    eml = 'eml'
    msg = 'msg'
    p7s = 'p7s'
    epub = 'epub'
    xls = 'xls'
    xlsx = 'xlsx'
    html = 'html'
    htm = 'htm'
    bmp = 'bmp'
    heic = 'heic'
    jpeg = 'jpeg'
    png = 'png'
    tiff = 'tiff'
    jpg = 'jpg'
    svg = 'svg'
    md = 'md'
    org = 'org'
    odt = 'odt'
    pdf = 'pdf'
    txt = 'txt'
    json = 'json'
    ppt = 'ppt'
    pptx = 'pptx'
    rst = 'rst'
    rtf = 'rtf'
    tsv = 'tsv'
    gif = 'gif'
    doc = 'doc'
    docx = 'docx'
    py = 'py'
    js = 'js'
    ts = 'ts'
    css = 'css'


class EmbeddingBlock(BaseModel):
    """
    A positionally-aligned masked embedding matrix.
    """

    dim: int = Field(0, title='Dim')
    encoding: Literal['raw-f32-base64'] = Field('raw-f32-base64', title='Encoding')
    mask_b64: str = Field('', title='Mask B64')
    values_b64: str = Field('', title='Values B64')


class EngramKind(Enum):
    """
    The canonical engram discriminator.

    A single source of truth: every engram is either a ``document`` or a
    ``conversation``. The kind drives which typed substructure
    (``Engram.document`` / ``Engram.conversation``) carries kind-specific
    fields. The free-form ``metadata`` dict is reserved for user-supplied
    annotations and is never inspected for routing.
    """

    document = 'document'
    conversation = 'conversation'


class EntityRecord(BaseModel):
    """
    Canonical entity record used in snapshots, WAL ops, and segments.
    """

    category: str | None = Field(None, title='Category')
    chunk_ids: list[str] | None = Field(None, title='Chunk Ids')
    collection_id: str = Field('', title='Collection Id')
    created_at: datetime = Field(..., title='Created At')
    description: str | None = Field(None, title='Description')
    engram_id: str = Field(..., title='Engram Id')
    fts_terms: dict[str, int] | None = Field(None, title='Fts Terms')
    id: str = Field(..., title='Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    relationship_count: int = Field(0, title='Relationship Count')
    updated_at: datetime = Field(..., title='Updated At')


class Error(BaseModel):
    """
    Canonical error response envelope used across all public endpoints. SDK error classes are generated from this shape.
    """

    code: str | None = Field(
        None, description='Optional fine-grained error code within a category.'
    )
    details: Any | None = Field(
        None,
        description='Optional structured payload with context-specific diagnostic data.',
    )
    message: str = Field(..., description='Human-readable error description.')
    request_id: str | None = Field(
        None, description='Request correlation id for support-ticket lookups.'
    )
    type: str = Field(
        ...,
        description="Stable machine-readable error category, e.g. 'validation_error', 'not_found', 'rate_limited'.",
    )


class EvidenceRecallRequest(BaseModel):
    """
    Expand a specific pattern's canonical instance subgraph.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    collection_id: UUID = Field(
        ...,
        description='Collection containing the patterns to recall.',
        title='Collection Id',
    )
    intent: Literal['evidence'] = Field('evidence', title='Intent')
    pattern_id: UUID = Field(
        ..., description='The pattern entity to hydrate.', title='Pattern Id'
    )
    top_k: int = Field(
        10, description='Maximum number of pattern hits to return.', title='Top K'
    )


class EvidenceRefType(Enum):
    chunk = 'chunk'
    table_artifact = 'table_artifact'


class Type(Enum):
    """
    Content kind: file, image, audio, or document.
    """

    file = 'file'
    image = 'image'
    audio = 'audio'
    document = 'document'


class FileContentRequest(BaseModel):
    """
    Unified file content for multimodal messages.
    """

    data: str = Field(..., description='Base64 encoded file data', title='Data')
    duration_seconds: float | None = Field(
        None, description='Duration in seconds (for audio)', title='Duration Seconds'
    )
    filename: str | None = Field(
        None, description='Original filename', title='Filename'
    )
    media_type: str = Field(
        'application/octet-stream', description='MIME type', title='Media Type'
    )
    type: Literal['audio', 'document', 'file', 'image'] = Field(
        ..., description='Content kind: file, image, audio, or document.', title='Type'
    )


class FileReferenceRequest(BaseModel):
    """
    Reference to a file uploaded through an upload session.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['file_ref'] = Field('file_ref', title='Type')
    upload_session_id: UUID = Field(
        ...,
        description='Upload session returned by memory.createUpload.',
        title='Upload Session Id',
    )


class ForbiddenPublicApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal['forbidden'] = Field(..., title='Code')
    details: None = Field(..., title='Details')
    message: str = Field(..., title='Message')
    request_id: str | None = Field(..., title='Request Id')
    type: Literal['forbidden'] = Field(..., title='Type')


class GenericMessageResponse(BaseModel):
    id: str | None = Field(None, title='Id')
    memory_id: str | None = Field(None, title='Memory Id')
    message: str = Field(..., title='Message')


class GraphExtractionProgressPhase(Enum):
    """
    Current work phase for per-engram graph extraction progress.
    """

    queued = 'queued'
    extracting = 'extracting'
    writing = 'writing'
    completed = 'completed'
    failed = 'failed'


class GraphExtractionStatus(Enum):
    """
    Status of graph creation per document.
    """

    pending = 'pending'
    processing = 'processing'
    empty = 'empty'
    success = 'success'
    failed = 'failed'


class InferenceHint(BaseModel):
    """
    A lightweight inference artifact returned alongside MemoryRecall.

    These are *not* asserted facts. They are "evidence + weak hints" that may have influenced
    retrieval (e.g. query expansion) or may be useful for UI transparency.
    """

    confidence: float | None = Field(None, title='Confidence')
    inference_metadata: dict[str, Any] | None = Field(None, title='Inference Metadata')
    inferred: bool = Field(False, title='Inferred')
    ledger_p_stable: float | None = Field(None, title='Ledger P Stable')
    ledger_p_true: float | None = Field(None, title='Ledger P True')
    ledger_p_use: float | None = Field(None, title='Ledger P Use')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    object: str = Field(..., title='Object')
    object_id: UUID | None = Field(None, title='Object Id')
    predicate: str = Field(..., title='Predicate')
    relationship_id: UUID | None = Field(None, title='Relationship Id')
    subject_id: UUID | None = Field(None, title='Subject Id')
    term: str = Field(..., title='Term')
    usable_for_rewrite: bool = Field(False, title='Usable For Rewrite')
    used_for_rewrite: bool = Field(False, title='Used For Rewrite')


class IngestionConfig(BaseModel):
    """
    Public ingestion config accepted by memory-ingestion endpoints.

    This mirrors the supported request payload shape while staying independent
    from the runtime provider config, which also carries internal-only fields
    such as ``app`` and ``extra_fields``.
    """

    audio_transcription_model: str | None = Field(
        None, title='Audio Transcription Model'
    )
    automatic_extraction: bool = Field(False, title='Automatic Extraction')
    chunk_enrichment_settings: ChunkEnrichmentSettings | None = None
    chunk_overlap: int = Field(512, title='Chunk Overlap')
    chunk_size: int = Field(1024, title='Chunk Size')
    chunking_strategy: str = Field('recursive', title='Chunking Strategy')
    excluded_parsers: list[str] | None = Field(None, title='Excluded Parsers')
    extra_parsers: dict[str, Any] | None = Field(None, title='Extra Parsers')
    max_concurrent_vlm_tasks: int = Field(5, title='Max Concurrent Vlm Tasks')
    parser_overrides: dict[str, str] | None = Field(None, title='Parser Overrides')
    provider: str = Field('nebula', title='Provider')
    vlm: str | None = Field(None, title='Vlm')
    vlm_batch_size: int = Field(5, title='Vlm Batch Size')
    vlm_max_tokens_to_sample: int = Field(1024, title='Vlm Max Tokens To Sample')
    vlm_ocr_one_page_per_chunk: bool = Field(True, title='Vlm Ocr One Page Per Chunk')


class IngestionFailureCode(Enum):
    """
    Stable, machine-readable reasons why ingestion stopped.
    """

    ingestion_failed = 'ingestion_failed'
    orchestration_unavailable = 'orchestration_unavailable'
    orchestration_start_timeout = 'orchestration_start_timeout'


class IngestionFailureStage(Enum):
    """
    The ingestion boundary at which processing stopped.
    """

    orchestration = 'orchestration'
    queued = 'queued'
    parsing = 'parsing'
    extracting = 'extracting'
    chunking = 'chunking'
    embedding = 'embedding'
    augmenting = 'augmenting'
    storing = 'storing'


class IngestionResponse(BaseModel):
    engram_id: UUID = Field(
        ..., description='The ID of the engram that was ingested.', title='Engram Id'
    )
    message: str = Field(
        ...,
        description='A message describing the result of the ingestion request.',
        title='Message',
    )
    task_id: UUID | None = Field(
        None, description='The task ID of the ingestion request.', title='Task Id'
    )


class IngestionStatus(Enum):
    """
    Status of document processing.
    """

    pending = 'pending'
    parsing = 'parsing'
    extracting = 'extracting'
    chunking = 'chunking'
    embedding = 'embedding'
    augmenting = 'augmenting'
    storing = 'storing'
    failed = 'failed'
    success = 'success'


class MemoryDeletingResult(CollectionDeletingResult):
    pass


class MemoryDeletionFailureCode(Enum):
    not_found_or_forbidden = 'not_found_or_forbidden'


class MemoryIdentityConflictPublicApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal['memory_identity_conflict'] = Field(..., title='Code')
    details: None = Field(..., title='Details')
    message: str = Field(..., title='Message')
    request_id: str | None = Field(..., title='Request Id')
    type: Literal['conflict'] = Field(..., title='Type')


class Query(RootModel[str]):
    root: str = Field(
        ...,
        description='Natural-language search query. Mutually exclusive with ``nql``.',
        max_length=4096,
        title='Query',
    )


class MemoryStoreFailureCode(Enum):
    invalid_memory = 'invalid_memory'
    processing_failed = 'processing_failed'
    collection_deleting = 'collection_deleting'


class MemoryStoreProcessingResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    failure: None = Field(..., title='Failure')
    id: UUID = Field(..., title='Id')
    state: Literal['processing'] = Field(..., title='State')


class MemoryStoreSearchableResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    failure: None = Field(..., title='Failure')
    id: UUID = Field(..., title='Id')
    state: Literal['searchable'] = Field(..., title='State')


class MessageType(Enum):
    system = 'system'
    user = 'user'
    assistant = 'assistant'
    function = 'function'
    tool = 'tool'


class MultipartUploadPartResponse(BaseModel):
    expires_in: int = Field(..., title='Expires In')
    part_number: int = Field(..., title='Part Number')
    upload_headers: dict[str, str] = Field(..., title='Upload Headers')
    upload_url: str = Field(..., title='Upload Url')


class MultipartUploadSessionResponse(BaseModel):
    expires_in: int = Field(..., title='Expires In')
    max_size: int = Field(..., title='Max Size')
    part_size: int = Field(
        ..., description='Recommended upload part size in bytes.', title='Part Size'
    )
    upload_session_id: UUID = Field(
        ...,
        description='Upload session ID to reference in memory creation.',
        title='Upload Session Id',
    )


class PaginatedCollectionResponse(BaseModel):
    """
    Cursor-paginated list of CollectionResponse entries. The wire envelope is ``{data, next_cursor, has_more}``.
    """

    data: list[CollectionResponse]
    has_more: bool = Field(
        ..., description='Whether another page is available after this one.'
    )
    next_cursor: str | None = Field(
        None,
        description='Opaque cursor for the next page. ``null`` when the caller has reached the end.',
    )


class PredictRecallRequest(BaseModel):
    """
    Cursor-style match plus the predicted next trace per pattern.

    The "predicted next" is the canonical instance's first trace,
    surfaced verbatim. This is correct for the matched-at-entry case
    -- recall matches when the user's state aligns with a pattern's
    entry state, so the canonical instance's first trace IS the next
    step. Mid-instance prediction (advance past offset 1) is NOT
    modelled in this version; callers that need it should follow up
    on the returned pattern with a dedicated trace-chain walk.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    collection_id: UUID = Field(
        ...,
        description='Collection containing the patterns to recall.',
        title='Collection Id',
    )
    intent: Literal['predict'] = Field('predict', title='Intent')
    state_id: UUID | None = Field(
        None,
        description="Anchor: the user's current state nodegroup id.",
        title='State Id',
    )
    top_k: int = Field(
        10, description='Maximum number of pattern hits to return.', title='Top K'
    )
    trace_id: UUID | None = Field(
        None,
        description="Anchor: the user's most recent trace id. The handler resolves this trace's state_before automatically.",
        title='Trace Id',
    )


class RelationshipRecord(BaseModel):
    """
    Canonical relationship record used in snapshots, WAL ops, and segments.
    """

    category: str | None = Field(None, title='Category')
    chunk_ids: list[str] | None = Field(None, title='Chunk Ids')
    collection_id: str = Field('', title='Collection Id')
    created_at: datetime = Field(..., title='Created At')
    description: str | None = Field(None, title='Description')
    engram_id: str | None = Field(None, title='Engram Id')
    id: str = Field(..., title='Id')
    inference_metadata: dict[str, Any] | None = Field(None, title='Inference Metadata')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    object: str | None = Field(None, title='Object')
    object_id: str = Field(..., title='Object Id')
    predicate: str = Field('', title='Predicate')
    relationship_type: str | None = Field(None, title='Relationship Type')
    subject: str | None = Field(None, title='Subject')
    subject_id: str = Field(..., title='Subject Id')
    temporal_precision: str | None = Field(None, title='Temporal Precision')
    updated_at: datetime = Field(..., title='Updated At')
    valid_span: dict[str, Any] | None = Field(None, title='Valid Span')
    weight: float | None = Field(None, title='Weight')


class ResourceNotFoundPublicApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal['resource_not_found'] = Field(..., title='Code')
    details: None = Field(..., title='Details')
    message: str = Field(..., title='Message')
    request_id: str | None = Field(..., title='Request Id')
    type: Literal['not_found'] = Field(..., title='Type')


class ResumeRecallRequest(BaseModel):
    """
    Cursor-style match biased toward deeper / further-along instances.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    collection_id: UUID = Field(
        ...,
        description='Collection containing the patterns to recall.',
        title='Collection Id',
    )
    intent: Literal['resume'] = Field('resume', title='Intent')
    state_id: UUID | None = Field(
        None,
        description="Anchor: the user's current state nodegroup id.",
        title='State Id',
    )
    top_k: int = Field(
        10, description='Maximum number of pattern hits to return.', title='Top K'
    )
    trace_id: UUID | None = Field(
        None,
        description="Anchor: the user's most recent trace id. The handler resolves this trace's state_before automatically.",
        title='Trace Id',
    )


class MemoryKind(Enum):
    semantic = 'semantic'
    episodic = 'episodic'
    procedural = 'procedural'


class Status1(Enum):
    complete = 'complete'
    partial = 'partial'


class RetryAfterDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    retry_after_seconds: int = Field(..., title='Retry After Seconds')


class SearchEffort(Enum):
    """
    Compute effort budget for memory search.

    Effort controls traversal compute (exploration budgets, depth, fanout), not the
    size of the returned MemoryRecall projection.
    """

    auto = 'auto'
    low = 'low'
    medium = 'medium'
    high = 'high'


class SearchSettings(BaseModel):
    """
    Advanced search settings for fine-tuning search behavior.

    Note: Core parameters (query, collection_ids, filters) are now top-level API parameters.
    This class contains advanced tuning options plus internal fields used by the retrieval service.

    Memory search uses `effort` (auto/low/medium/high) to control compute.
    """

    effort: SearchEffort = Field(
        'auto',
        description='Compute effort budget (auto/low/medium/high). Controls traversal compute for memory search, not MemoryRecall size.',
    )
    enable_conceptual_expansion: bool = Field(
        False,
        description='Enable conceptual expansion for cross-domain discovery through overlapping concepts',
        title='Enable Conceptual Expansion',
    )
    filters: dict[str, Any] | None = Field(
        None,
        description='Internal: Filters populated by the API router',
        title='Filters',
    )
    fulltext_weight: float = Field(
        0.2,
        description='Weight for fulltext search in hybrid mode (0-1). Set to 0 for pure semantic search.',
        ge=0.0,
        le=1.0,
        title='Fulltext Weight',
    )
    graph_settings: dict[str, Any] | None = Field(
        None,
        description='Internal: Graph traversal settings (bfs_max_depth, semantic_threshold, etc.)',
        title='Graph Settings',
    )
    has_pruning_gate: bool = Field(
        False,
        description='Internal: Set by select_search_filters when an owner_id $in partition-pruning wrapper has been added around the filter tree. Used by the in-memory graph read engine to strip the Postgres-only wrapper before evaluating delegation.',
        title='Has Pruning Gate',
    )
    include_scores: bool = Field(
        True,
        description='Whether to include search score values in the search results',
        title='Include Scores',
    )
    semantic_weight: float = Field(
        0.8,
        description='Weight for semantic search in hybrid mode (0-1). Set to 0 for pure fulltext search.',
        ge=0.0,
        le=1.0,
        title='Semantic Weight',
    )
    verbose: bool = Field(
        False,
        description='Include full internal metadata, UUIDs, and confidence fields in MemoryRecall responses. When False, returns compact LLM-optimized format.',
        title='Verbose',
    )


class ServiceUnavailablePublicApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal['service_unavailable'] = Field(..., title='Code')
    details: RetryAfterDetails
    message: str = Field(..., title='Message')
    request_id: str | None = Field(..., title='Request Id')
    type: Literal['service_unavailable'] = Field(..., title='Type')


class SnapshotImportResult(BaseModel):
    """
    Ephemeral collection handle returned after importing a snapshot.
    """

    ephemeral_collection_id: UUID = Field(..., title='Ephemeral Collection Id')


class SnapshotObjectReference(BaseModel):
    """
    Customer-owned snapshot object transport for device memory.
    """

    collection_id: UUID = Field(
        ...,
        description='Collection UUID the referenced snapshot belongs to. Nebula authorizes this collection before fetching customer-owned URLs.',
        title='Collection Id',
    )
    get_headers: dict[str, str] | None = Field(None, title='Get Headers')
    get_url: str | None = Field(
        None,
        description='Short-lived signed URL Nebula can GET to load the snapshot.',
        title='Get Url',
    )
    put_headers: dict[str, str] | None = Field(None, title='Put Headers')
    put_url: str | None = Field(
        None,
        description='Short-lived signed URL Nebula can PUT to store an updated snapshot.',
        title='Put Url',
    )
    type: Literal['signed_url'] = Field('signed_url', title='Type')


class SnapshotSearchEntityResponse(BaseModel):
    category: str | None = Field(None, title='Category')
    description: str | None = Field(None, title='Description')
    id: UUID = Field(..., title='Id')
    name: str = Field(..., title='Name')
    score: float = Field(..., title='Score')


class SnapshotSearchRelationshipResponse(BaseModel):
    description: str | None = Field(None, title='Description')
    id: UUID = Field(..., title='Id')
    object_id: UUID = Field(..., title='Object Id')
    predicate: str = Field(..., title='Predicate')
    subject_id: UUID = Field(..., title='Subject Id')
    weight: float | None = Field(None, title='Weight')


class SnapshotSearchResult(BaseModel):
    """
    Stateless snapshot-search response shape.
    """

    entities: list[SnapshotSearchEntityResponse] | None = Field(None, title='Entities')
    relationships: list[SnapshotSearchRelationshipResponse] | None = Field(
        None, title='Relationships'
    )


class SourceProvenance(BaseModel):
    name: str | None = Field(
        None,
        description='Human-readable source title, such as a filename or subject.',
        title='Name',
    )
    provider: str | None = Field(
        None,
        description="Connector/provider identifier, such as 'gmail' or 'google_drive'.",
        title='Provider',
    )
    provider_object_id: str | None = Field(
        None,
        description='Provider-native id for the source item.',
        title='Provider Object Id',
    )
    provider_parent_id: str | None = Field(
        None,
        description='Provider-native id of the parent source item.',
        title='Provider Parent Id',
    )
    provider_thread_id: str | None = Field(
        None,
        description='Provider-native id for the thread/conversation.',
        title='Provider Thread Id',
    )
    type: str | None = Field(
        None,
        description="Human-scale source class, such as 'file', 'email', or 'chat'.",
        title='Type',
    )
    uri: str | None = Field(
        None, description='Stable non-URL source identifier.', title='Uri'
    )
    url: str | None = Field(
        None,
        description='Provider URL for the source object when available.',
        title='Url',
    )


class StorageTargetCreateRequest(BaseModel):
    """
    Hosted SaaS storage target registration. Use AWS S3 and omit custom endpoint configuration.
    """

    bucket: str = Field(..., max_length=255, min_length=1, title='Bucket')
    kms_key_id: str | None = Field(None, max_length=2048, title='Kms Key Id')
    name: str = Field(..., max_length=128, min_length=1, title='Name')
    prefix: str = Field('', max_length=1024, title='Prefix')
    region: str = Field(..., max_length=64, title='Region')
    role_arn: str = Field(
        ...,
        description='AWS IAM role ARN Nebula assumes to access the bucket.',
        max_length=2048,
        title='Role Arn',
    )


class StorageTargetPlanRequiredDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    collection_id: UUID = Field(..., title='Collection Id')
    workspace_id: UUID = Field(..., title='Workspace Id')


class StorageTargetPlanRequiredPublicApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal['storage_target_plan_required'] = Field(..., title='Code')
    details: StorageTargetPlanRequiredDetails
    message: str = Field(..., title='Message')
    request_id: str | None = Field(..., title='Request Id')
    type: Literal['forbidden'] = Field(..., title='Type')


class Status2(Enum):
    pending = 'pending'
    active = 'active'
    validation_failed = 'validation_failed'
    disabled = 'disabled'


class StorageTargetResponse(BaseModel):
    bucket: str = Field(..., title='Bucket')
    created_at: datetime = Field(..., title='Created At')
    external_id: str = Field(..., title='External Id')
    id: UUID = Field(..., title='Id')
    kind: Literal['customer_s3'] = Field(..., title='Kind')
    kms_key_id: str | None = Field(None, title='Kms Key Id')
    last_validated_at: datetime | None = Field(None, title='Last Validated At')
    name: str = Field(..., title='Name')
    prefix: str = Field(..., title='Prefix')
    region: str | None = Field(None, title='Region')
    role_arn: str | None = Field(None, title='Role Arn')
    status: Status2 = Field(..., title='Status')
    updated_at: datetime = Field(..., title='Updated At')
    validation_error: str | None = Field(None, title='Validation Error')
    workspace_id: UUID = Field(..., title='Workspace Id')


class StorageTargetUnavailableDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    collection_id: UUID = Field(..., title='Collection Id')
    storage_target_id: UUID = Field(..., title='Storage Target Id')


class StorageTargetUnavailablePublicApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal['storage_target_unavailable'] = Field(..., title='Code')
    details: StorageTargetUnavailableDetails
    message: str = Field(..., title='Message')
    request_id: str | None = Field(..., title='Request Id')
    type: Literal['conflict'] = Field(..., title='Type')


class Chunks1Item(Chunk):
    pass


class Chunks1(RootModel[list[Chunks1Item]]):
    root: list[Chunks1Item] = Field(
        ...,
        description='Pre-chunked text for a document memory.',
        min_length=1,
        title='Chunks',
    )


class RawText1(RootModel[str]):
    root: str = Field(
        ...,
        description='Raw text for a document memory.',
        min_length=1,
        pattern='[\\s\\S]*\\S[\\s\\S]*',
        title='Raw Text',
    )


class Chunks2Item(Chunk):
    pass


class Chunks2(RootModel[list[Chunks2Item]]):
    root: list[Chunks2Item] = Field(
        ...,
        description='Pre-chunked text for a document memory.',
        min_length=1,
        title='Chunks',
    )


class TextContentRequest(BaseModel):
    """
    Text content block.
    """

    text: str = Field(
        ...,
        description='Text content',
        min_length=1,
        pattern='[\\s\\S]*\\S[\\s\\S]*',
        title='Text',
    )
    type: Literal['text'] = Field('text', title='Type')


class Name(RootModel[str]):
    root: str = Field(
        ..., max_length=256, min_length=1, pattern='[\\s\\S]*\\S[\\s\\S]*', title='Name'
    )


class UpdateCollectionRequest(BaseModel):
    access_tier: str | None = Field(None, title='Access Tier')
    description: str | None = Field(None, title='Description')
    generate_description: bool = Field(False, title='Generate Description')
    name: Name | None = Field(None, title='Name')
    workflows_enabled: bool | None = Field(None, title='Workflows Enabled')


class UpdateMemoryRequest(BaseModel):
    collection_ids: list[UUID] | None = Field(
        None, description='New collection associations', title='Collection Ids'
    )
    merge_metadata: bool = Field(
        False, description='Merge with existing metadata', title='Merge Metadata'
    )
    metadata: dict[str, Any] | None = Field(
        None, description='Metadata to update', title='Metadata'
    )
    name: str | None = Field(None, description='New name for the memory', title='Name')


class ValidationIssue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str = Field(..., title='Code')
    message: str = Field(..., title='Message')
    path: list[str | int] = Field(..., title='Path')


class WorkflowRecallResponse(BaseModel):
    """
    Wrapped response for the workflow recall endpoint.

    The ``results`` payload shape varies per ``intent``:

    * ``cursor`` / ``predict`` / ``resume`` -- ``{intent, hits[]}``
      with ``hits`` containing pattern-match ranked entries.
      ``predict`` additionally carries ``predicted_next_by_pattern``.
    * ``evidence`` -- ``{intent, expanded}`` where ``expanded`` is the
      hydrated canonical-instance subgraph.
    * ``bootstrap`` -- ``{intent, hits[]}`` ranked by confidence with
      no anchor.

    The OpenAPI schema is intentionally typed as a generic object;
    consumers should branch on ``results.intent`` and read the keys
    documented in the request variants above.
    """

    results: dict[str, Any] = Field(
        ...,
        description='Per-intent payload; see class docstring for shape.',
        title='Results',
    )


class WorkspaceEncryptionStatus(Enum):
    pending = 'pending'
    provisioning = 'provisioning'
    activating = 'activating'
    activation_failed = 'activation_failed'
    active = 'active'
    disabling = 'disabling'
    disable_failed = 'disable_failed'
    validation_failed = 'validation_failed'
    disabled = 'disabled'


class WrappedCollectionResponse(BaseModel):
    results: CollectionResponse


class WrappedCompactMemoryRecallResponse(BaseModel):
    results: CompactMemoryRecallResponse


class WrappedCompleteMultipartUploadResponse(BaseModel):
    results: CompleteMultipartUploadResponse


class WrappedConnectorConnectResponse(BaseModel):
    results: ConnectorConnectResponse


class WrappedConnectorOAuthAppResponse(BaseModel):
    results: ConnectorOAuthAppResponse


class WrappedConnectorSyncResponse(BaseModel):
    results: ConnectorSyncResponse


class WrappedGenericMessageResponse(BaseModel):
    results: GenericMessageResponse


class WrappedIngestionResponse(BaseModel):
    results: IngestionResponse


class WrappedListOfConnectorOAuthAppResponse(BaseModel):
    results: list[ConnectorOAuthAppResponse] = Field(..., title='Results')


class WrappedListOfStorageTargetResponse(BaseModel):
    results: list[StorageTargetResponse] = Field(..., title='Results')


class WrappedListOfStr(BaseModel):
    results: list[str] = Field(..., title='Results')


class WrappedMultipartUploadPartResponse(BaseModel):
    results: MultipartUploadPartResponse


class WrappedMultipartUploadSessionResponse(BaseModel):
    results: MultipartUploadSessionResponse


class WrappedSnapshotImportResult(BaseModel):
    results: SnapshotImportResult


class WrappedSnapshotSearchResult(BaseModel):
    results: SnapshotSearchResult


class WrappedStorageTargetResponse(BaseModel):
    results: StorageTargetResponse


class WrongWriteRegionDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error_type: Literal['wrong_write_region'] = Field(..., title='Error Type')
    home_region: str = Field(..., title='Home Region')
    local_region: str = Field(..., title='Local Region')
    region_owner_epoch: int = Field(..., title='Region Owner Epoch')
    subject: str = Field(..., title='Subject')
    subject_id: UUID = Field(..., title='Subject Id')


class WrongWriteRegionPublicApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal['wrong_write_region'] = Field(..., title='Code')
    details: WrongWriteRegionDetails
    message: str = Field(..., title='Message')
    request_id: str | None = Field(..., title='Request Id')
    type: Literal['misdirected_request'] = Field(..., title='Type')


class ActivatedWorkflow(BaseModel):
    """
    A workflow template activated during memory traversal.

    Workflows are the most structured form of procedure: ordered step
    sequences derived from Stage 2B causal subgraphs, clustered by
    taxonomy-triple backbone signature, and canonicalized via LLM-backed
    template induction.  They answer "walk me through how I do X" and
    "what comes after step Y" queries, as opposed to ActivatedProcedure
    which answers "what are my preferences about X".
    """

    activation_score: float = Field(0, title='Activation Score')
    active_instance_count: int = Field(0, title='Active Instance Count')
    backbone_signature_hash: str | None = Field(None, title='Backbone Signature Hash')
    branches: list[dict[str, Any]] | None = Field(None, title='Branches')
    confidence: float = Field(0, title='Confidence')
    current_step_index: int | None = Field(None, title='Current Step Index')
    goal: str = Field(..., title='Goal')
    id: UUID = Field(..., title='Id')
    instance_count: int = Field(0, title='Instance Count')
    last_observed_at: str | None = Field(None, title='Last Observed At')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    predicted_next_step: ActivatedWorkflowStep | None = None
    steps: list[ActivatedWorkflowStep] | None = Field(None, title='Steps')
    taxonomy_version: int = Field(1, title='Taxonomy Version')
    variable_slots: dict[str, Any] | None = Field(None, title='Variable Slots')


class Content11(
    RootModel[TextContentRequest | FileContentRequest | FileReferenceRequest]
):
    root: TextContentRequest | FileContentRequest | FileReferenceRequest = Field(
        ..., discriminator='type'
    )


class Content1(RootModel[list[Content11]]):
    root: list[Content11] = Field(
        ...,
        description='Message content. Use a string for text-only messages or a list of content parts for multimodal content.',
        min_length=1,
        title='Content',
    )


class AppendConversationMessage(BaseModel):
    authority: Authority | None = Field(
        None, description='Optional authority score', title='Authority'
    )
    content: Content | Content1 = Field(
        ...,
        description='Message content. Use a string for text-only messages or a list of content parts for multimodal content.',
        title='Content',
    )
    metadata: dict[str, Any] | None = Field(
        None, description='Optional message-level metadata', title='Metadata'
    )
    parent_id: UUID | None = Field(
        None, description='Optional parent message ID', title='Parent Id'
    )
    role: Role = Field(
        ..., description="Role: 'user', 'assistant', or 'system'", title='Role'
    )
    source_role_id: UUID | None = Field(
        None, description='Optional SourceRole entity ID', title='Source Role Id'
    )
    timestamp: datetime | None = Field(
        None,
        description="Semantic timestamp for when the message was authored. Drives chunk timestamps, the extraction LLM's temporal anchor, and episodic grouping. Without it, relative phrases ('this morning') resolve against ingestion wall-clock and episodes collapse.",
        title='Timestamp',
    )


class Messages(RootModel[list[AppendConversationMessage]]):
    root: list[AppendConversationMessage] = Field(
        ...,
        description='Messages to append for conversation memories. Each message has content, role, and optional metadata.',
        min_length=1,
        title='Messages',
    )


class AppendMemoryRequest(BaseModel):
    chunks: Chunks | None = Field(
        None,
        description='Pre-processed text chunks to append for document memories.',
        title='Chunks',
    )
    collection_id: UUID = Field(
        ...,
        description='Target collection ID for the appended content.',
        title='Collection Id',
    )
    ingestion_config: IngestionConfig | None = Field(
        None, description='Optional ingestion configuration override.'
    )
    messages: Messages | None = Field(
        None,
        description='Messages to append for conversation memories. Each message has content, role, and optional metadata.',
        title='Messages',
    )
    metadata: dict[str, Any] | None = Field(
        None,
        description='Additional metadata for the appended content.',
        title='Metadata',
    )
    raw_text: RawText | None = Field(
        None,
        description='Raw text content to append for document memories.',
        title='Raw Text',
    )


class CollectionMutationFailure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: CollectionMutationFailureCode
    message: str = Field(..., title='Message')


class CompleteMultipartUploadRequest(BaseModel):
    expected_sha256: str = Field(
        ...,
        description='Full-object SHA-256 hex digest.',
        pattern='^[0-9a-f]{64}$',
        title='Expected Sha256',
    )
    parts: list[CompletedMultipartUploadPart] = Field(..., min_length=1, title='Parts')


class ConnectorConnectionResponse(BaseModel):
    collection_id: UUID = Field(..., title='Collection Id')
    config: dict[str, Any] | None = Field(None, title='Config')
    created_at: datetime = Field(..., title='Created At')
    error_detail: ConnectorErrorDetail | None = None
    external_account_id: str | None = Field(None, title='External Account Id')
    health: Health | None = Field(None, title='Health')
    id: UUID = Field(..., title='Id')
    is_syncing: bool = Field(False, title='Is Syncing')
    items_synced: int | None = Field(None, title='Items Synced')
    last_error: str | None = Field(None, title='Last Error')
    last_synced_at: datetime | None = Field(None, title='Last Synced At')
    next_sync_at: datetime | None = Field(None, title='Next Sync At')
    provider: str = Field(..., title='Provider')
    status: Status = Field(..., title='Status')
    sync_cursor: dict[str, Any] | None = Field(None, title='Sync Cursor')
    token_expires_at: datetime | None = Field(None, title='Token Expires At')
    updated_at: datetime = Field(..., title='Updated At')
    user_id: UUID = Field(..., title='User Id')
    uses_workspace_oauth_app: bool = Field(False, title='Uses Workspace Oauth App')


class ConnectorDisconnectResponse(BaseModel):
    message: str = Field(..., title='Message')
    warnings: list[ConnectorWarning] | None = Field(None, title='Warnings')


class Content31(Content11):
    pass


class Content3(RootModel[list[Content31]]):
    root: list[Content31] = Field(
        ...,
        description='Message content. Use a string for text-only messages or a list of content parts for multimodal content.',
        min_length=1,
        title='Content',
    )


class ConversationMessage(BaseModel):
    """
    A message in a conversation with multimodal support.
    """

    authority: Authority | None = Field(
        None, description='Optional authority score', title='Authority'
    )
    content: Content | Content3 = Field(
        ...,
        description='Message content. Use a string for text-only messages or a list of content parts for multimodal content.',
        title='Content',
    )
    metadata: dict[str, Any] | None = Field(
        None, description='Optional message-level metadata', title='Metadata'
    )
    role: Role = Field(
        ..., description="Role: 'user', 'assistant', or 'system'", title='Role'
    )
    timestamp: datetime | None = Field(
        None,
        description="Semantic timestamp for when the message was authored. Drives chunk timestamps, the extraction LLM's temporal anchor, and episodic grouping. Without it, relative phrases ('this morning') resolve against ingestion wall-clock and episodes collapse.",
        title='Timestamp',
    )


class DocumentFields(BaseModel):
    """
    Document-specific typed fields.

    Present iff ``Engram.kind == DOCUMENT``. ``document_type`` is required
    because every document needs an extension/format classifier for parsing.
    ``original_extension`` records the source filename's extension when it
    differs from the canonical ``document_type`` (e.g. user uploaded ``.JPG``
    normalized to ``jpeg``).
    """

    document_type: DocumentType
    original_extension: str | None = Field(None, title='Original Extension')


class EvidenceRef(BaseModel):
    """
    Tagged reference to a source of evidence.
    """

    artifact_id: UUID | None = Field(None, title='Artifact Id')
    chunk_id: UUID | None = Field(None, title='Chunk Id')
    collection_id: UUID | None = Field(None, title='Collection Id')
    column_names: list[str] | None = Field(None, title='Column Names')
    ref_type: EvidenceRefType
    row_indices: list[int] | None = Field(None, title='Row Indices')
    table_name: str | None = Field(None, title='Table Name')


class GraphExtractionProgress(BaseModel):
    """
    Per-engram graph extraction progress for the latest extraction manifest.
    """

    batch_submitted_groups: int = Field(0, title='Batch Submitted Groups')
    completed_groups: int = Field(0, title='Completed Groups')
    failed_groups: int = Field(0, title='Failed Groups')
    in_flight_groups: int = Field(0, title='In Flight Groups')
    last_updated_at: datetime | None = Field(None, title='Last Updated At')
    pending_groups: int = Field(0, title='Pending Groups')
    phase: GraphExtractionProgressPhase = 'queued'
    progress: float = Field(0, ge=0.0, le=1.0, title='Progress')
    status: GraphExtractionStatus = 'pending'
    total_groups: int = Field(0, title='Total Groups')


class GraphPayload(BaseModel):
    """
    A complete graph payload or a context subgraph payload.
    """

    entities: list[EntityRecord] | None = Field(None, title='Entities')
    entity_description_embeddings: EmbeddingBlock | None = None
    relationship_description_embeddings: EmbeddingBlock | None = None
    relationship_relation_embeddings: EmbeddingBlock | None = None
    relationships: list[RelationshipRecord] | None = Field(None, title='Relationships')


class GroundedSource(BaseModel):
    """
    A source that grounds facts in episodic memory.

    This is the raw source material that supports the structured knowledge.
    Provides the exact quotes and context for verification.

    ``evidence_ref`` carries typed provenance so the client can distinguish
    chunk-backed sources from table-artifact-backed sources (or future
    modalities) without parsing opaque metadata.
    """

    activation_score: float = Field(0, title='Activation Score')
    display_name: str | None = Field(None, title='Display Name')
    engram_id: UUID | None = Field(None, title='Engram Id')
    evidence_ref: EvidenceRef | None = None
    id: UUID = Field(..., title='Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    owner_id: UUID | None = Field(None, title='Owner Id')
    page_number: int | None = Field(None, title='Page Number')
    section_path: list[str] | None = Field(None, title='Section Path')
    source: SourceProvenance | None = None
    source_role: str | None = Field(None, title='Source Role')
    speaker: str | None = Field(None, title='Speaker')
    speaker_id: UUID | None = Field(None, title='Speaker Id')
    structure_label: str | None = Field(None, title='Structure Label')
    supporting_fact_ids: list[UUID] | None = Field(None, title='Supporting Fact Ids')
    text: str = Field(..., title='Text')
    timestamp: datetime | None = Field(None, title='Timestamp')


class IngestionFailure(BaseModel):
    """
    Sanitized public failure details for a failed ingestion attempt.
    """

    code: IngestionFailureCode
    message: str = Field(..., max_length=500, min_length=1, title='Message')
    occurred_at: datetime = Field(..., title='Occurred At')
    retryable: bool = Field(..., title='Retryable')
    stage: IngestionFailureStage
    workflow_run_id: str | None = Field(None, title='Workflow Run Id')


class ListedEngram(BaseModel):
    """
    Engram as it appears in list responses, with per-row chunk-page metadata appended.
    """

    chunks: list | None = Field(None, title='Chunks')
    chunks_truncated: bool | None = Field(
        None,
        description="True when ``chunks`` carries a prefix of the engram's full chunk set; fetch ``/v1/memories/{id}/chunks`` for the rest.",
    )
    collection_ids: list[UUID] | None = Field(None, title='Collection Ids')
    conversation: ConversationFields | None = None
    created_at: datetime | None = Field(None, title='Created At')
    document: DocumentFields | None = None
    extraction_status: GraphExtractionStatus = 'pending'
    generation: int = Field(1, ge=1, title='Generation')
    graph_extraction_progress: GraphExtractionProgress | None = None
    id: UUID | None = Field(None, title='Id')
    ingestion_attempt_number: int | None = Field(None, title='Ingestion Attempt Number')
    ingestion_failure: IngestionFailure | None = None
    ingestion_status: IngestionStatus = 'pending'
    kind: EngramKind
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    owner_id: UUID = Field(..., title='Owner Id')
    search_ready_seq: int | None = Field(None, title='Search Ready Seq')
    size_in_bytes: int | None = Field(None, title='Size In Bytes')
    text: str | None = Field(None, title='Text')
    title: str | None = Field(None, title='Title')
    total_chunks: int | None = Field(
        None, description='Total chunks for this engram across the collection.'
    )
    total_tokens: int | None = Field(None, title='Total Tokens')
    updated_at: datetime | None = Field(None, title='Updated At')
    version: str | None = Field(None, title='Version')
    workflow_run_id: str | None = Field(None, title='Workflow Run Id')


class MemoryDeletionFailure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: MemoryDeletionFailureCode
    message: str = Field(..., title='Message')


class MemoryStoreFailure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: MemoryStoreFailureCode
    message: str = Field(..., title='Message')


class Message(BaseModel):
    content: Any = Field(None, title='Content')
    function_call: dict[str, Any] | None = Field(None, title='Function Call')
    image_data: dict[str, str] | None = Field(None, title='Image Data')
    image_url: str | None = Field(None, title='Image Url')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str | None = Field(None, title='Name')
    role: MessageType | str = Field(..., title='Role')
    structured_content: list[dict[str, Any]] | None = Field(
        None, title='Structured Content'
    )
    tool_call_id: str | None = Field(None, title='Tool Call Id')
    tool_calls: list[dict[str, Any]] | None = Field(None, title='Tool Calls')


class PaginatedListedEngram(BaseModel):
    """
    Cursor-paginated list of ListedEngram entries. The wire envelope is ``{data, next_cursor, has_more}``.
    """

    data: list[ListedEngram]
    has_more: bool = Field(
        ..., description='Whether another page is available after this one.'
    )
    next_cursor: str | None = Field(
        None,
        description='Opaque cursor for the next page. ``null`` when the caller has reached the end.',
    )


class PublicValidationErrorDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    issues: list[ValidationIssue] = Field(..., title='Issues')


class RateLimitedPublicApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal['rate_limited'] = Field(..., title='Code')
    details: RetryAfterDetails
    message: str = Field(..., title='Message')
    request_id: str | None = Field(..., title='Request Id')
    type: Literal['rate_limited'] = Field(..., title='Type')


class SnapshotEnvelopeInput(BaseModel):
    """
    Portable full snapshot owned by the client.
    """

    collection_id: UUID = Field(..., title='Collection Id')
    created_at: datetime | None = Field(None, title='Created At')
    format_version: Literal[4] = Field(4, title='Format Version')
    generation: int = Field(0, title='Generation')
    graph: GraphPayload | None = None
    root_hash: str = Field(..., title='Root Hash')


class SnapshotEnvelopeOutput(SnapshotEnvelopeInput):
    """
    Portable full snapshot owned by the client.
    """


class SnapshotExportRequest(BaseModel):
    collection_id: UUID = Field(..., title='Collection Id')
    destination: SnapshotObjectReference | None = None


class SnapshotImportRequest(BaseModel):
    snapshot: SnapshotEnvelopeInput | None = None
    snapshot_ref: SnapshotObjectReference | None = None


class ContentParts1(Content11):
    pass


class ContentParts(RootModel[list[ContentParts1]]):
    root: list[ContentParts1] = Field(
        ...,
        description='Multimodal content for a document memory.',
        min_length=1,
        title='Content Parts',
    )


class Messages1(RootModel[list[ConversationMessage]]):
    root: list[ConversationMessage] = Field(
        ...,
        description='Messages for a conversation memory.',
        min_length=1,
        title='Messages',
    )


class StoreMemoryBatchItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chunks: Chunks1 | None = Field(
        None, description='Pre-chunked text for a document memory.', title='Chunks'
    )
    content_parts: ContentParts | None = Field(
        None,
        description='Multimodal content for a document memory.',
        title='Content Parts',
    )
    ingestion_config: IngestionConfig | None = Field(
        None, description='Custom document ingestion configuration.'
    )
    kind: EngramKind = Field(
        'document',
        description='Memory kind. When omitted, conversation is inferred when messages are present; otherwise document is inferred.',
    )
    memory_id: UUID = Field(
        ...,
        description='Stable memory identity generated automatically by Nebula SDKs.',
        title='Memory Id',
    )
    messages: Messages1 | None = Field(
        None, description='Messages for a conversation memory.', title='Messages'
    )
    metadata: dict[str, Any] | None = Field(
        None, description='User-supplied memory metadata.', title='Metadata'
    )
    name: str | None = Field(None, title='Name')
    raw_text: RawText1 | None = Field(
        None, description='Raw text for a document memory.', title='Raw Text'
    )
    speaker_id: UUID | None = Field(None, title='Speaker Id')
    speaker_name: str | None = Field(None, title='Speaker Name')


class ContentParts21(Content11):
    pass


class ContentParts2(RootModel[list[ContentParts21]]):
    root: list[ContentParts21] = Field(
        ...,
        description='Multimodal content for a document memory.',
        min_length=1,
        title='Content Parts',
    )


class StoreMemoryRequest(BaseModel):
    """
    Store one collection-backed memory.

    The memory identity is generated and frozen by Nebula SDKs before the
    request is serialized, so transport retries recover the same durable write.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    chunks: Chunks2 | None = Field(
        None, description='Pre-chunked text for a document memory.', title='Chunks'
    )
    collection_id: UUID = Field(
        ..., description='Collection that owns the memory.', title='Collection Id'
    )
    content_parts: ContentParts2 | None = Field(
        None,
        description='Multimodal content for a document memory.',
        title='Content Parts',
    )
    ingestion_config: IngestionConfig | None = Field(
        None, description='Custom document ingestion configuration.'
    )
    kind: EngramKind = Field(
        'document',
        description='Memory kind. When omitted, conversation is inferred when messages are present; otherwise document is inferred.',
    )
    memory_id: UUID = Field(
        ...,
        description='Stable memory identity generated automatically by Nebula SDKs.',
        title='Memory Id',
    )
    messages: Messages1 | None = Field(
        None, description='Messages for a conversation memory.', title='Messages'
    )
    metadata: dict[str, Any] | None = Field(
        None, description='User-supplied memory metadata.', title='Metadata'
    )
    name: str | None = Field(None, title='Name')
    raw_text: RawText1 | None = Field(
        None, description='Raw text for a document memory.', title='Raw Text'
    )
    speaker_id: UUID | None = Field(None, title='Speaker Id')
    speaker_name: str | None = Field(None, title='Speaker Name')


class UnavailableRetrievalAuditSource(BaseModel):
    """
    Retained evidence reference whose source can no longer be resolved.
    """

    evidence_ref: EvidenceRef
    status: Literal['unavailable'] = Field(..., title='Status')


class ValidationPublicApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal['validation_error'] = Field(..., title='Code')
    details: PublicValidationErrorDetails
    message: str = Field(..., title='Message')
    request_id: str | None = Field(..., title='Request Id')
    type: Literal['validation_error'] = Field(..., title='Type')


class WorkspaceEncryptionResponse(BaseModel):
    active_propagation_id: UUID | None = Field(None, title='Active Propagation Id')
    created_at: datetime = Field(..., title='Created At')
    kms_key_id: str | None = Field(None, title='Kms Key Id')
    last_validated_at: datetime | None = Field(None, title='Last Validated At')
    propagation_completed_items: int | None = Field(
        None, title='Propagation Completed Items'
    )
    propagation_failed_items: int | None = Field(None, title='Propagation Failed Items')
    propagation_last_error: str | None = Field(None, title='Propagation Last Error')
    propagation_operation: str | None = Field(None, title='Propagation Operation')
    propagation_status: str | None = Field(None, title='Propagation Status')
    propagation_total_items: int | None = Field(None, title='Propagation Total Items')
    status: WorkspaceEncryptionStatus
    updated_at: datetime = Field(..., title='Updated At')
    validation_error: str | None = Field(None, title='Validation Error')
    workspace_id: UUID = Field(..., title='Workspace Id')


class WrappedConnectorConnectionResponse(BaseModel):
    results: ConnectorConnectionResponse


class WrappedConnectorDisconnectResponse(BaseModel):
    results: ConnectorDisconnectResponse


class WrappedListOfConnectorConnectionResponse(BaseModel):
    results: list[ConnectorConnectionResponse] = Field(..., title='Results')


class WrappedSnapshotEnvelopeOrSnapshotObjectReference(BaseModel):
    results: SnapshotEnvelopeOutput | SnapshotObjectReference = Field(
        ..., title='Results'
    )


class WrappedWorkspaceEncryptionResponse(BaseModel):
    results: WorkspaceEncryptionResponse


class ActivatedSemantic(BaseModel):
    """
    A semantic item activated during memory traversal.

    Represents a structured assertion (fact, inference, or episodic) that was
    found relevant to the query. Links back to its entity and source
    utterances for provenance.
    """

    activation_score: float = Field(0, title='Activation Score')
    category: str = Field('fact', title='Category')
    corroboration_count: int = Field(1, title='Corroboration Count')
    description: str | None = Field(None, title='Description')
    entity_id: UUID | None = Field(None, title='Entity Id')
    entity_name: str | None = Field(None, title='Entity Name')
    evidence_ids: list[UUID] | None = Field(None, title='Evidence Ids')
    evidence_refs: list[EvidenceRef] | None = Field(None, title='Evidence Refs')
    extraction_confidence: float = Field(0, title='Extraction Confidence')
    id: UUID = Field(..., title='Id')
    is_current: bool | None = Field(None, title='Is Current')
    memory_class: str | None = Field(None, title='Memory Class')
    predicate: str = Field(..., title='Predicate')
    reasoning: str | None = Field(None, title='Reasoning')
    resolved_at: datetime | None = Field(None, title='Resolved At')
    source_nodegroup_ids: list[UUID] | None = Field(None, title='Source Nodegroup Ids')
    stability_confidence: float | None = Field(None, title='Stability Confidence')
    subject: str = Field(..., title='Subject')
    temporal_precision: str | None = Field(None, title='Temporal Precision')
    temporal_validity: Any = Field(None, title='Temporal Validity')
    truth_confidence: float | None = Field(None, title='Truth Confidence')
    use_confidence: float | None = Field(None, title='Use Confidence')
    value: str = Field(..., title='Value')


class AppendMemoryResponse(BaseModel):
    appended_messages: list[AppendedMessageResponse] | None = Field(
        None, title='Appended Messages'
    )
    id: UUID = Field(..., title='Id')
    message: Message
    metadata: dict[str, Any] = Field({}, title='Metadata')


class AvailableRetrievalAuditSource(BaseModel):
    """
    Hydrated source that remains available to the authorized caller.
    """

    activation_score: float = Field(..., title='Activation Score')
    display_name: str | None = Field(None, title='Display Name')
    evidence_ref: EvidenceRef
    id: UUID = Field(..., title='Id')
    speaker: str | None = Field(None, title='Speaker')
    status: Literal['available'] = Field(..., title='Status')
    supporting_fact_ids: list[UUID] = Field(..., title='Supporting Fact Ids')
    text: str = Field(..., title='Text')
    timestamp: datetime | None = Field(None, title='Timestamp')


class CollectionFailedResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    failure: CollectionMutationFailure
    id: UUID = Field(..., title='Id')
    state: Literal['failed'] = Field(..., title='State')


class CollectionMutationResult(
    RootModel[
        CollectionProvisioningResult
        | CollectionActiveResult
        | CollectionDeletingResult
        | CollectionDeletedResult
        | CollectionFailedResult
    ]
):
    root: (
        CollectionProvisioningResult
        | CollectionActiveResult
        | CollectionDeletingResult
        | CollectionDeletedResult
        | CollectionFailedResult
    ) = Field(..., discriminator='state', title='CollectionMutationResult')


class Engram(BaseModel):
    """
    The unified engram model: typed kind + per-kind substructure.

    ``kind`` is the canonical discriminator. The per-kind ``conversation``
    and ``document`` substructures hold typed fields known to the
    platform; ``metadata`` is reserved for user-supplied annotations and
    must never carry platform-written discriminators or routing markers.

    Construction enforces shape consistency via a model validator:
    ``kind=conversation`` must not carry document fields, ``kind=document``
    must carry a ``DocumentFields`` substructure (``document_type`` is
    required), and vice versa.
    """

    chunks: list | None = Field(None, title='Chunks')
    collection_ids: list[UUID] | None = Field(None, title='Collection Ids')
    conversation: ConversationFields | None = None
    created_at: datetime | None = Field(None, title='Created At')
    document: DocumentFields | None = None
    extraction_status: GraphExtractionStatus = 'pending'
    generation: int = Field(1, ge=1, title='Generation')
    graph_extraction_progress: GraphExtractionProgress | None = None
    id: UUID | None = Field(None, title='Id')
    ingestion_attempt_number: int | None = Field(None, title='Ingestion Attempt Number')
    ingestion_failure: IngestionFailure | None = None
    ingestion_status: IngestionStatus = 'pending'
    kind: EngramKind
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    owner_id: UUID = Field(..., title='Owner Id')
    search_ready_seq: int | None = Field(None, title='Search Ready Seq')
    size_in_bytes: int | None = Field(None, title='Size In Bytes')
    text: str | None = Field(None, title='Text')
    title: str | None = Field(None, title='Title')
    total_tokens: int | None = Field(None, title='Total Tokens')
    updated_at: datetime | None = Field(None, title='Updated At')
    version: str | None = Field(None, title='Version')
    workflow_run_id: str | None = Field(None, title='Workflow Run Id')


class MemoryDeletionFailedResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    failure: MemoryDeletionFailure
    id: UUID = Field(..., title='Id')
    state: Literal['failed'] = Field(..., title='State')


class MemoryDeletionResult(
    RootModel[MemoryDeletingResult | MemoryDeletionFailedResult]
):
    root: MemoryDeletingResult | MemoryDeletionFailedResult = Field(
        ..., discriminator='state', title='MemoryDeletionResult'
    )


class MemoryRecall(BaseModel):
    """
    Hierarchical memory response - all layers, weighted by activation.

    This is the primary response type for conceptual memory retrieval.
    It contains all layers of the memory hierarchy:

    1. **Entities (gestalt/schema layer)**: EntityProfiles that represent
       the conceptual understanding of activated entities.

    2. **Semantics (semantic layer)**: Structured assertions (facts,
       inferences, tasks) scored by relevance and confidence.

    3. **Episodes (temporal clusters)**: Episodic nodegroups that cluster
       temporally related facts and events.

    4. **Sources (episodic layer)**: The raw source material that
       grounds the structured knowledge in actual moments/quotes.
    """

    entities: list[ActivatedEntity] | None = Field(None, title='Entities')
    episodic: list[ActivatedEpisode] | None = Field(None, title='Episodic')
    inference_hints: list[InferenceHint] | None = Field(None, title='Inference Hints')
    procedural: list[ActivatedProcedure] | None = Field(None, title='Procedural')
    query: str = Field(..., title='Query')
    retrieval_id: UUID | None = Field(
        None,
        description='Stable identifier for retrieval audit and follow-up source resolution.',
        title='Retrieval Id',
    )
    search_timing_ms: dict[str, float] | None = Field(None, title='Search Timing Ms')
    semantic: list[ActivatedSemantic] | None = Field(None, title='Semantic')
    sources: list[GroundedSource] | None = Field(None, title='Sources')
    total_traversal_time_ms: float | None = Field(None, title='Total Traversal Time Ms')
    workflows: list[ActivatedWorkflow] | None = Field(None, title='Workflows')


class MemorySearchRequest(BaseModel):
    """
    Request model for memory search.

    Callers must supply exactly one of ``query`` or ``nql``. ``query``
    takes the planner path; ``nql`` executes a hand-written script
    directly for deterministic test/tooling use cases.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    collection_ids: list[str] | None = Field(
        None,
        description='Optional list of collection UUIDs or names to scope the search.',
        title='Collection Ids',
    )
    effort: SearchEffort | None = Field(
        None,
        description='Compute effort budget (auto/low/medium/high). Controls traversal compute, not MemoryRecall size.',
    )
    filters: dict[str, Any] | None = Field(
        None, description='Optional filters to apply to the search.', title='Filters'
    )
    include_sources: bool = Field(
        False,
        description='Include the raw source material that grounds the retrieved memory. Sources are omitted by default to keep responses compact.',
        title='Include Sources',
    )
    nql: str | None = Field(
        None,
        description='Pre-written NQL script. Executes directly without planner compilation. Mutually exclusive with ``query``.',
        title='Nql',
    )
    query: Query | None = Field(
        None,
        description='Natural-language search query. Mutually exclusive with ``nql``.',
        title='Query',
    )
    retrieval_operation_id: UUID | None = Field(
        None,
        description='Stable identifier for one logical retrieval. Reuse it when retrying the same request so retrieval evidence remains idempotent.',
        title='Retrieval Operation Id',
    )
    search_settings: SearchSettings | None = Field(
        None, description='Advanced search settings.'
    )
    snapshot: SnapshotEnvelopeInput | None = Field(
        None, description='Device-memory snapshot for stateless search.'
    )
    snapshot_ref: SnapshotObjectReference | None = Field(
        None, description='Device-memory snapshot reference for stateless search.'
    )
    workspace_id: UUID | None = Field(
        None,
        description="Workspace that owns this search audit and request log. When set, the search is constrained to collections in that workspace. Unspecified searches are attributed to the caller's personal workspace.",
        title='Workspace Id',
    )


class MemoryStoreFailedResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    failure: MemoryStoreFailure
    id: UUID = Field(..., title='Id')
    state: Literal['failed'] = Field(..., title='State')


class MemoryStoreResult(
    RootModel[
        MemoryStoreProcessingResult
        | MemoryStoreSearchableResult
        | MemoryStoreFailedResult
    ]
):
    root: (
        MemoryStoreProcessingResult
        | MemoryStoreSearchableResult
        | MemoryStoreFailedResult
    ) = Field(..., discriminator='state', title='MemoryStoreResult')


class PublicApiError(
    RootModel[
        ForbiddenPublicApiError
        | ResourceNotFoundPublicApiError
        | CollectionProvisioningPublicApiError
        | CollectionDeletingPublicApiError
        | CollectionFailedPublicApiError
        | CollectionIdentityConflictPublicApiError
        | MemoryIdentityConflictPublicApiError
        | CollectionQuotaExceededPublicApiError
        | CollectionNameConflictPublicApiError
        | StorageTargetUnavailablePublicApiError
        | StorageTargetPlanRequiredPublicApiError
        | WrongWriteRegionPublicApiError
        | ValidationPublicApiError
        | RateLimitedPublicApiError
        | ServiceUnavailablePublicApiError
    ]
):
    root: (
        ForbiddenPublicApiError
        | ResourceNotFoundPublicApiError
        | CollectionProvisioningPublicApiError
        | CollectionDeletingPublicApiError
        | CollectionFailedPublicApiError
        | CollectionIdentityConflictPublicApiError
        | MemoryIdentityConflictPublicApiError
        | CollectionQuotaExceededPublicApiError
        | CollectionNameConflictPublicApiError
        | StorageTargetUnavailablePublicApiError
        | StorageTargetPlanRequiredPublicApiError
        | WrongWriteRegionPublicApiError
        | ValidationPublicApiError
        | RateLimitedPublicApiError
        | ServiceUnavailablePublicApiError
    ) = Field(..., discriminator='code', title='PublicApiError')


class RetrievalAuditSourceGroup(BaseModel):
    """
    Sources supporting one result returned by the original search.
    """

    activation_score: float = Field(..., title='Activation Score')
    memory_id: UUID = Field(..., title='Memory Id')
    memory_kind: MemoryKind = Field(..., title='Memory Kind')
    rank: int = Field(..., ge=0, title='Rank')
    sources: list[Annotated[AvailableRetrievalAuditSource | UnavailableRetrievalAuditSource, Field(discriminator='status')]] = Field(..., title='Sources')
    truncated: bool = Field(False, title='Truncated')


class RetrievalAuditSourcesResponse(BaseModel):
    """
    Authorization-checked sources for a previously audited retrieval.
    """

    groups: list[RetrievalAuditSourceGroup] = Field(..., title='Groups')
    retrieval_id: UUID = Field(..., title='Retrieval Id')
    status: Status1 = Field(..., title='Status')


class StoreMemoriesRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    collection_id: UUID = Field(
        ..., description='Collection that owns the memories.', title='Collection Id'
    )
    memories: list[StoreMemoryBatchItem] = Field(
        ..., max_length=40, min_length=1, title='Memories'
    )


class StoreMemoriesResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    memories: list[Annotated[MemoryStoreProcessingResult | MemoryStoreSearchableResult | MemoryStoreFailedResult, Field(discriminator='state')]] = Field(..., title='Memories')


class WrappedAppendMemoryResponse(BaseModel):
    results: AppendMemoryResponse


class WrappedCollectionMutationResult(BaseModel):
    results: CollectionMutationResult


class WrappedEngram(BaseModel):
    results: Engram


class WrappedMemoryDeletionResult(BaseModel):
    results: MemoryDeletionResult


class WrappedMemoryRecall(BaseModel):
    results: MemoryRecall


class WrappedMemoryStoreResult(BaseModel):
    results: MemoryStoreResult


class WrappedRetrievalAuditSourcesResponse(BaseModel):
    results: RetrievalAuditSourcesResponse


class WrappedStoreMemoriesResult(BaseModel):
    results: StoreMemoriesResult


class DeleteMemoriesResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    memories: list[Annotated[MemoryDeletingResult | MemoryDeletionFailedResult, Field(discriminator='state')]] = Field(..., title='Memories')


class WrappedDeleteMemoriesResult(BaseModel):
    results: DeleteMemoriesResult
