# AUTOGENERATED by nebula-sdks/generator. Do not edit by hand.
# Source: nebula-sdks/openapi/openapi.json

from __future__ import annotations

from typing import Any, TypeAlias

from pydantic import ValidationError

from .. import _models as models

PublicApiError: TypeAlias = models.PublicApiError


def parse_public_api_error(value: Any) -> PublicApiError | None:
    try:
        return models.PublicApiError.model_validate(value)
    except (ValidationError, ValueError):
        return None
